/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IDiamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamond__factory>;
    getContractFactory(
      name: "IDiamondCut",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondCut__factory>;
    getContractFactory(
      name: "IDiamondLoupe",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondLoupe__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC173",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC173__factory>;
    getContractFactory(
      name: "IIFtso",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIFtso__factory>;
    getContractFactory(
      name: "FtsoV2Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FtsoV2Interface__factory>;
    getContractFactory(
      name: "IFtsoGenesis",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFtsoGenesis__factory>;
    getContractFactory(
      name: "IFtsoManagerGenesis",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFtsoManagerGenesis__factory>;
    getContractFactory(
      name: "IFtsoRegistryGenesis",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFtsoRegistryGenesis__factory>;
    getContractFactory(
      name: "IAddressValidityVerification",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAddressValidityVerification__factory>;
    getContractFactory(
      name: "IAgentAlwaysAllowedMinters",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentAlwaysAllowedMinters__factory>;
    getContractFactory(
      name: "IAgentPing",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentPing__factory>;
    getContractFactory(
      name: "IAgentVaultsFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentVaultsFacet__factory>;
    getContractFactory(
      name: "IAssetManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAssetManager__factory>;
    getContractFactory(
      name: "IAssetManagerController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAssetManagerController__factory>;
    getContractFactory(
      name: "IAssetManagerEvents",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAssetManagerEvents__factory>;
    getContractFactory(
      name: "IBalanceDecreasingTransactionVerification",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBalanceDecreasingTransactionVerification__factory>;
    getContractFactory(
      name: "IClaimSetupManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IClaimSetupManager__factory>;
    getContractFactory(
      name: "IConfirmedBlockHeightExistsVerification",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IConfirmedBlockHeightExistsVerification__factory>;
    getContractFactory(
      name: "ICoreVaultClient",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICoreVaultClient__factory>;
    getContractFactory(
      name: "ICoreVaultClientSettings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICoreVaultClientSettings__factory>;
    getContractFactory(
      name: "IDelegationAccount",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDelegationAccount__factory>;
    getContractFactory(
      name: "IDirectMinting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDirectMinting__factory>;
    getContractFactory(
      name: "IDirectMintingSettings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDirectMintingSettings__factory>;
    getContractFactory(
      name: "IEntityManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IEntityManager__factory>;
    getContractFactory(
      name: "IEVMTransactionVerification",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IEVMTransactionVerification__factory>;
    getContractFactory(
      name: "IExecutorsFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IExecutorsFacet__factory>;
    getContractFactory(
      name: "IFastUpdateIncentiveManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFastUpdateIncentiveManager__factory>;
    getContractFactory(
      name: "IFastUpdater",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFastUpdater__factory>;
    getContractFactory(
      name: "IFastUpdatesConfiguration",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFastUpdatesConfiguration__factory>;
    getContractFactory(
      name: "IFdcHub",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFdcHub__factory>;
    getContractFactory(
      name: "IFdcInflationConfigurations",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFdcInflationConfigurations__factory>;
    getContractFactory(
      name: "IFdcRequestFeeConfigurations",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFdcRequestFeeConfigurations__factory>;
    getContractFactory(
      name: "IFdcVerification",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFdcVerification__factory>;
    getContractFactory(
      name: "IFeeCalculator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFeeCalculator__factory>;
    getContractFactory(
      name: "IFlareAssetRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFlareAssetRegistry__factory>;
    getContractFactory(
      name: "IFlareContractRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFlareContractRegistry__factory>;
    getContractFactory(
      name: "IFlareSystemsCalculator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFlareSystemsCalculator__factory>;
    getContractFactory(
      name: "IFlareSystemsManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFlareSystemsManager__factory>;
    getContractFactory(
      name: "IFtso",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFtso__factory>;
    getContractFactory(
      name: "IFtsoFeedDecimals",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFtsoFeedDecimals__factory>;
    getContractFactory(
      name: "IFtsoFeedIdConverter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFtsoFeedIdConverter__factory>;
    getContractFactory(
      name: "IFtsoFeedPublisher",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFtsoFeedPublisher__factory>;
    getContractFactory(
      name: "IFtsoInflationConfigurations",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFtsoInflationConfigurations__factory>;
    getContractFactory(
      name: "IFtsoManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFtsoManager__factory>;
    getContractFactory(
      name: "IFtsoRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFtsoRegistry__factory>;
    getContractFactory(
      name: "IFtsoRewardManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFtsoRewardManager__factory>;
    getContractFactory(
      name: "IFtsoRewardOffersManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFtsoRewardOffersManager__factory>;
    getContractFactory(
      name: "IGenericRewardManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGenericRewardManager__factory>;
    getContractFactory(
      name: "IGovernanceSettings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGovernanceSettings__factory>;
    getContractFactory(
      name: "IGovernanceVotePower",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGovernanceVotePower__factory>;
    getContractFactory(
      name: "IIncreaseManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIncreaseManager__factory>;
    getContractFactory(
      name: "IInstructionFeesFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IInstructionFeesFacet__factory>;
    getContractFactory(
      name: "IInstructionsFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IInstructionsFacet__factory>;
    getContractFactory(
      name: "IMasterAccountController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMasterAccountController__factory>;
    getContractFactory(
      name: "IMemoInstructionsFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMemoInstructionsFacet__factory>;
    getContractFactory(
      name: "IPauseFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPauseFacet__factory>;
    getContractFactory(
      name: "IPaymentProofsFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPaymentProofsFacet__factory>;
    getContractFactory(
      name: "IPaymentVerification",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPaymentVerification__factory>;
    getContractFactory(
      name: "IPChainStakeMirror",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPChainStakeMirror__factory>;
    getContractFactory(
      name: "IPChainVotePower",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPChainVotePower__factory>;
    getContractFactory(
      name: "IPersonalAccountsFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPersonalAccountsFacet__factory>;
    getContractFactory(
      name: "IPriceSubmitter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPriceSubmitter__factory>;
    getContractFactory(
      name: "IRandomProvider",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRandomProvider__factory>;
    getContractFactory(
      name: "IReaderFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IReaderFacet__factory>;
    getContractFactory(
      name: "IRedeemExtended",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRedeemExtended__factory>;
    getContractFactory(
      name: "IRedeemExtendedSettings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRedeemExtendedSettings__factory>;
    getContractFactory(
      name: "IRedemptionTimeExtension",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRedemptionTimeExtension__factory>;
    getContractFactory(
      name: "IReferencedPaymentNonexistenceVerification",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IReferencedPaymentNonexistenceVerification__factory>;
    getContractFactory(
      name: "IRelay",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRelay__factory>;
    getContractFactory(
      name: "IRewardManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRewardManager__factory>;
    getContractFactory(
      name: "ISubmission",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISubmission__factory>;
    getContractFactory(
      name: "ITimelockFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITimelockFacet__factory>;
    getContractFactory(
      name: "IVaultsFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVaultsFacet__factory>;
    getContractFactory(
      name: "IVoterRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVoterRegistry__factory>;
    getContractFactory(
      name: "IVoterWhitelister",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVoterWhitelister__factory>;
    getContractFactory(
      name: "IVPContractEvents",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVPContractEvents__factory>;
    getContractFactory(
      name: "IVPToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVPToken__factory>;
    getContractFactory(
      name: "IWeb2JsonVerification",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWeb2JsonVerification__factory>;
    getContractFactory(
      name: "IWNat",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWNat__factory>;
    getContractFactory(
      name: "IWNatDelegationFee",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWNatDelegationFee__factory>;
    getContractFactory(
      name: "IXrplProviderWalletsFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IXrplProviderWalletsFacet__factory>;
    getContractFactory(
      name: "IXRPPaymentNonexistenceVerification",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IXRPPaymentNonexistenceVerification__factory>;
    getContractFactory(
      name: "IXRPPaymentVerification",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IXRPPaymentVerification__factory>;
    getContractFactory(
      name: "ProtocolsV2Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProtocolsV2Interface__factory>;
    getContractFactory(
      name: "RandomNumberV2Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RandomNumberV2Interface__factory>;
    getContractFactory(
      name: "RewardsV2Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RewardsV2Interface__factory>;
    getContractFactory(
      name: "TestFtsoV2Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestFtsoV2Interface__factory>;
    getContractFactory(
      name: "IICleanable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IICleanable__factory>;
    getContractFactory(
      name: "IIGovernanceVotePower",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIGovernanceVotePower__factory>;
    getContractFactory(
      name: "IIVPContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIVPContract__factory>;
    getContractFactory(
      name: "IIVPToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIVPToken__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1363__factory>;
    getContractFactory(
      name: "IBeacon",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBeacon__factory>;
    getContractFactory(
      name: "ERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155__factory>;
    getContractFactory(
      name: "IERC1155MetadataURI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155MetadataURI__factory>;
    getContractFactory(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155__factory>;
    getContractFactory(
      name: "IERC1155Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Receiver__factory>;
    getContractFactory(
      name: "ERC1155Holder",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155Holder__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeERC20__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeCast__factory>;
    getContractFactory(
      name: "IOutcomeResolver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IOutcomeResolver__factory>;
    getContractFactory(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC20__factory>;
    getContractFactory(
      name: "PolycastOracleMinter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PolycastOracleMinter__factory>;
    getContractFactory(
      name: "PolycastOracleMinterFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PolycastOracleMinterFactory__factory>;
    getContractFactory(
      name: "PolymarketPriceOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PolymarketPriceOracle__factory>;
    getContractFactory(
      name: "PolycastAMM",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PolycastAMM__factory>;
    getContractFactory(
      name: "PolycastAMMFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PolycastAMMFactory__factory>;
    getContractFactory(
      name: "PolycastMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PolycastMarket__factory>;
    getContractFactory(
      name: "PolycastMarketFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PolycastMarketFactory__factory>;
    getContractFactory(
      name: "FdcWeb2JsonResolver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FdcWeb2JsonResolver__factory>;
    getContractFactory(
      name: "FtsoPriceResolver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FtsoPriceResolver__factory>;
    getContractFactory(
      name: "ManualResolver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ManualResolver__factory>;

    getContractAt(
      name: "IDiamond",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamond>;
    getContractAt(
      name: "IDiamondCut",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondCut>;
    getContractAt(
      name: "IDiamondLoupe",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondLoupe>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IERC173",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC173>;
    getContractAt(
      name: "IIFtso",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIFtso>;
    getContractAt(
      name: "FtsoV2Interface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FtsoV2Interface>;
    getContractAt(
      name: "IFtsoGenesis",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFtsoGenesis>;
    getContractAt(
      name: "IFtsoManagerGenesis",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFtsoManagerGenesis>;
    getContractAt(
      name: "IFtsoRegistryGenesis",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFtsoRegistryGenesis>;
    getContractAt(
      name: "IAddressValidityVerification",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAddressValidityVerification>;
    getContractAt(
      name: "IAgentAlwaysAllowedMinters",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentAlwaysAllowedMinters>;
    getContractAt(
      name: "IAgentPing",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentPing>;
    getContractAt(
      name: "IAgentVaultsFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentVaultsFacet>;
    getContractAt(
      name: "IAssetManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAssetManager>;
    getContractAt(
      name: "IAssetManagerController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAssetManagerController>;
    getContractAt(
      name: "IAssetManagerEvents",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAssetManagerEvents>;
    getContractAt(
      name: "IBalanceDecreasingTransactionVerification",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBalanceDecreasingTransactionVerification>;
    getContractAt(
      name: "IClaimSetupManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IClaimSetupManager>;
    getContractAt(
      name: "IConfirmedBlockHeightExistsVerification",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IConfirmedBlockHeightExistsVerification>;
    getContractAt(
      name: "ICoreVaultClient",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICoreVaultClient>;
    getContractAt(
      name: "ICoreVaultClientSettings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICoreVaultClientSettings>;
    getContractAt(
      name: "IDelegationAccount",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDelegationAccount>;
    getContractAt(
      name: "IDirectMinting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDirectMinting>;
    getContractAt(
      name: "IDirectMintingSettings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDirectMintingSettings>;
    getContractAt(
      name: "IEntityManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IEntityManager>;
    getContractAt(
      name: "IEVMTransactionVerification",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IEVMTransactionVerification>;
    getContractAt(
      name: "IExecutorsFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IExecutorsFacet>;
    getContractAt(
      name: "IFastUpdateIncentiveManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFastUpdateIncentiveManager>;
    getContractAt(
      name: "IFastUpdater",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFastUpdater>;
    getContractAt(
      name: "IFastUpdatesConfiguration",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFastUpdatesConfiguration>;
    getContractAt(
      name: "IFdcHub",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFdcHub>;
    getContractAt(
      name: "IFdcInflationConfigurations",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFdcInflationConfigurations>;
    getContractAt(
      name: "IFdcRequestFeeConfigurations",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFdcRequestFeeConfigurations>;
    getContractAt(
      name: "IFdcVerification",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFdcVerification>;
    getContractAt(
      name: "IFeeCalculator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFeeCalculator>;
    getContractAt(
      name: "IFlareAssetRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFlareAssetRegistry>;
    getContractAt(
      name: "IFlareContractRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFlareContractRegistry>;
    getContractAt(
      name: "IFlareSystemsCalculator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFlareSystemsCalculator>;
    getContractAt(
      name: "IFlareSystemsManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFlareSystemsManager>;
    getContractAt(
      name: "IFtso",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFtso>;
    getContractAt(
      name: "IFtsoFeedDecimals",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFtsoFeedDecimals>;
    getContractAt(
      name: "IFtsoFeedIdConverter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFtsoFeedIdConverter>;
    getContractAt(
      name: "IFtsoFeedPublisher",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFtsoFeedPublisher>;
    getContractAt(
      name: "IFtsoInflationConfigurations",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFtsoInflationConfigurations>;
    getContractAt(
      name: "IFtsoManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFtsoManager>;
    getContractAt(
      name: "IFtsoRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFtsoRegistry>;
    getContractAt(
      name: "IFtsoRewardManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFtsoRewardManager>;
    getContractAt(
      name: "IFtsoRewardOffersManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFtsoRewardOffersManager>;
    getContractAt(
      name: "IGenericRewardManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGenericRewardManager>;
    getContractAt(
      name: "IGovernanceSettings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGovernanceSettings>;
    getContractAt(
      name: "IGovernanceVotePower",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGovernanceVotePower>;
    getContractAt(
      name: "IIncreaseManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIncreaseManager>;
    getContractAt(
      name: "IInstructionFeesFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IInstructionFeesFacet>;
    getContractAt(
      name: "IInstructionsFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IInstructionsFacet>;
    getContractAt(
      name: "IMasterAccountController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMasterAccountController>;
    getContractAt(
      name: "IMemoInstructionsFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMemoInstructionsFacet>;
    getContractAt(
      name: "IPauseFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPauseFacet>;
    getContractAt(
      name: "IPaymentProofsFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPaymentProofsFacet>;
    getContractAt(
      name: "IPaymentVerification",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPaymentVerification>;
    getContractAt(
      name: "IPChainStakeMirror",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPChainStakeMirror>;
    getContractAt(
      name: "IPChainVotePower",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPChainVotePower>;
    getContractAt(
      name: "IPersonalAccountsFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPersonalAccountsFacet>;
    getContractAt(
      name: "IPriceSubmitter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPriceSubmitter>;
    getContractAt(
      name: "IRandomProvider",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRandomProvider>;
    getContractAt(
      name: "IReaderFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IReaderFacet>;
    getContractAt(
      name: "IRedeemExtended",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRedeemExtended>;
    getContractAt(
      name: "IRedeemExtendedSettings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRedeemExtendedSettings>;
    getContractAt(
      name: "IRedemptionTimeExtension",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRedemptionTimeExtension>;
    getContractAt(
      name: "IReferencedPaymentNonexistenceVerification",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IReferencedPaymentNonexistenceVerification>;
    getContractAt(
      name: "IRelay",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRelay>;
    getContractAt(
      name: "IRewardManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRewardManager>;
    getContractAt(
      name: "ISubmission",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISubmission>;
    getContractAt(
      name: "ITimelockFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITimelockFacet>;
    getContractAt(
      name: "IVaultsFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVaultsFacet>;
    getContractAt(
      name: "IVoterRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVoterRegistry>;
    getContractAt(
      name: "IVoterWhitelister",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVoterWhitelister>;
    getContractAt(
      name: "IVPContractEvents",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVPContractEvents>;
    getContractAt(
      name: "IVPToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVPToken>;
    getContractAt(
      name: "IWeb2JsonVerification",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IWeb2JsonVerification>;
    getContractAt(
      name: "IWNat",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IWNat>;
    getContractAt(
      name: "IWNatDelegationFee",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IWNatDelegationFee>;
    getContractAt(
      name: "IXrplProviderWalletsFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IXrplProviderWalletsFacet>;
    getContractAt(
      name: "IXRPPaymentNonexistenceVerification",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IXRPPaymentNonexistenceVerification>;
    getContractAt(
      name: "IXRPPaymentVerification",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IXRPPaymentVerification>;
    getContractAt(
      name: "ProtocolsV2Interface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ProtocolsV2Interface>;
    getContractAt(
      name: "RandomNumberV2Interface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RandomNumberV2Interface>;
    getContractAt(
      name: "RewardsV2Interface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RewardsV2Interface>;
    getContractAt(
      name: "TestFtsoV2Interface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TestFtsoV2Interface>;
    getContractAt(
      name: "IICleanable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IICleanable>;
    getContractAt(
      name: "IIGovernanceVotePower",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIGovernanceVotePower>;
    getContractAt(
      name: "IIVPContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIVPContract>;
    getContractAt(
      name: "IIVPToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIVPToken>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "IERC1363",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1363>;
    getContractAt(
      name: "IBeacon",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBeacon>;
    getContractAt(
      name: "ERC1155",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155>;
    getContractAt(
      name: "IERC1155MetadataURI",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155MetadataURI>;
    getContractAt(
      name: "IERC1155",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155>;
    getContractAt(
      name: "IERC1155Receiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Receiver>;
    getContractAt(
      name: "ERC1155Holder",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155Holder>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "SafeERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeERC20>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "SafeCast",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeCast>;
    getContractAt(
      name: "IOutcomeResolver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IOutcomeResolver>;
    getContractAt(
      name: "MockERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC20>;
    getContractAt(
      name: "PolycastOracleMinter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PolycastOracleMinter>;
    getContractAt(
      name: "PolycastOracleMinterFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PolycastOracleMinterFactory>;
    getContractAt(
      name: "PolymarketPriceOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PolymarketPriceOracle>;
    getContractAt(
      name: "PolycastAMM",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PolycastAMM>;
    getContractAt(
      name: "PolycastAMMFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PolycastAMMFactory>;
    getContractAt(
      name: "PolycastMarket",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PolycastMarket>;
    getContractAt(
      name: "PolycastMarketFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PolycastMarketFactory>;
    getContractAt(
      name: "FdcWeb2JsonResolver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FdcWeb2JsonResolver>;
    getContractAt(
      name: "FtsoPriceResolver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FtsoPriceResolver>;
    getContractAt(
      name: "ManualResolver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ManualResolver>;

    deployContract(
      name: "IDiamond",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDiamond>;
    deployContract(
      name: "IDiamondCut",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDiamondCut>;
    deployContract(
      name: "IDiamondLoupe",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDiamondLoupe>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "IERC173",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC173>;
    deployContract(
      name: "IIFtso",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIFtso>;
    deployContract(
      name: "FtsoV2Interface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FtsoV2Interface>;
    deployContract(
      name: "IFtsoGenesis",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoGenesis>;
    deployContract(
      name: "IFtsoManagerGenesis",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoManagerGenesis>;
    deployContract(
      name: "IFtsoRegistryGenesis",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoRegistryGenesis>;
    deployContract(
      name: "IAddressValidityVerification",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAddressValidityVerification>;
    deployContract(
      name: "IAgentAlwaysAllowedMinters",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentAlwaysAllowedMinters>;
    deployContract(
      name: "IAgentPing",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentPing>;
    deployContract(
      name: "IAgentVaultsFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentVaultsFacet>;
    deployContract(
      name: "IAssetManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAssetManager>;
    deployContract(
      name: "IAssetManagerController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAssetManagerController>;
    deployContract(
      name: "IAssetManagerEvents",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAssetManagerEvents>;
    deployContract(
      name: "IBalanceDecreasingTransactionVerification",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBalanceDecreasingTransactionVerification>;
    deployContract(
      name: "IClaimSetupManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IClaimSetupManager>;
    deployContract(
      name: "IConfirmedBlockHeightExistsVerification",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IConfirmedBlockHeightExistsVerification>;
    deployContract(
      name: "ICoreVaultClient",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICoreVaultClient>;
    deployContract(
      name: "ICoreVaultClientSettings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICoreVaultClientSettings>;
    deployContract(
      name: "IDelegationAccount",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDelegationAccount>;
    deployContract(
      name: "IDirectMinting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDirectMinting>;
    deployContract(
      name: "IDirectMintingSettings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDirectMintingSettings>;
    deployContract(
      name: "IEntityManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEntityManager>;
    deployContract(
      name: "IEVMTransactionVerification",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEVMTransactionVerification>;
    deployContract(
      name: "IExecutorsFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IExecutorsFacet>;
    deployContract(
      name: "IFastUpdateIncentiveManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFastUpdateIncentiveManager>;
    deployContract(
      name: "IFastUpdater",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFastUpdater>;
    deployContract(
      name: "IFastUpdatesConfiguration",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFastUpdatesConfiguration>;
    deployContract(
      name: "IFdcHub",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFdcHub>;
    deployContract(
      name: "IFdcInflationConfigurations",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFdcInflationConfigurations>;
    deployContract(
      name: "IFdcRequestFeeConfigurations",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFdcRequestFeeConfigurations>;
    deployContract(
      name: "IFdcVerification",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFdcVerification>;
    deployContract(
      name: "IFeeCalculator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFeeCalculator>;
    deployContract(
      name: "IFlareAssetRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlareAssetRegistry>;
    deployContract(
      name: "IFlareContractRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlareContractRegistry>;
    deployContract(
      name: "IFlareSystemsCalculator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlareSystemsCalculator>;
    deployContract(
      name: "IFlareSystemsManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlareSystemsManager>;
    deployContract(
      name: "IFtso",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtso>;
    deployContract(
      name: "IFtsoFeedDecimals",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoFeedDecimals>;
    deployContract(
      name: "IFtsoFeedIdConverter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoFeedIdConverter>;
    deployContract(
      name: "IFtsoFeedPublisher",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoFeedPublisher>;
    deployContract(
      name: "IFtsoInflationConfigurations",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoInflationConfigurations>;
    deployContract(
      name: "IFtsoManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoManager>;
    deployContract(
      name: "IFtsoRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoRegistry>;
    deployContract(
      name: "IFtsoRewardManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoRewardManager>;
    deployContract(
      name: "IFtsoRewardOffersManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoRewardOffersManager>;
    deployContract(
      name: "IGenericRewardManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGenericRewardManager>;
    deployContract(
      name: "IGovernanceSettings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGovernanceSettings>;
    deployContract(
      name: "IGovernanceVotePower",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGovernanceVotePower>;
    deployContract(
      name: "IIncreaseManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIncreaseManager>;
    deployContract(
      name: "IInstructionFeesFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInstructionFeesFacet>;
    deployContract(
      name: "IInstructionsFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInstructionsFacet>;
    deployContract(
      name: "IMasterAccountController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMasterAccountController>;
    deployContract(
      name: "IMemoInstructionsFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMemoInstructionsFacet>;
    deployContract(
      name: "IPauseFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPauseFacet>;
    deployContract(
      name: "IPaymentProofsFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymentProofsFacet>;
    deployContract(
      name: "IPaymentVerification",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymentVerification>;
    deployContract(
      name: "IPChainStakeMirror",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPChainStakeMirror>;
    deployContract(
      name: "IPChainVotePower",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPChainVotePower>;
    deployContract(
      name: "IPersonalAccountsFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPersonalAccountsFacet>;
    deployContract(
      name: "IPriceSubmitter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPriceSubmitter>;
    deployContract(
      name: "IRandomProvider",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRandomProvider>;
    deployContract(
      name: "IReaderFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReaderFacet>;
    deployContract(
      name: "IRedeemExtended",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRedeemExtended>;
    deployContract(
      name: "IRedeemExtendedSettings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRedeemExtendedSettings>;
    deployContract(
      name: "IRedemptionTimeExtension",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRedemptionTimeExtension>;
    deployContract(
      name: "IReferencedPaymentNonexistenceVerification",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReferencedPaymentNonexistenceVerification>;
    deployContract(
      name: "IRelay",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRelay>;
    deployContract(
      name: "IRewardManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRewardManager>;
    deployContract(
      name: "ISubmission",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISubmission>;
    deployContract(
      name: "ITimelockFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITimelockFacet>;
    deployContract(
      name: "IVaultsFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVaultsFacet>;
    deployContract(
      name: "IVoterRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVoterRegistry>;
    deployContract(
      name: "IVoterWhitelister",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVoterWhitelister>;
    deployContract(
      name: "IVPContractEvents",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVPContractEvents>;
    deployContract(
      name: "IVPToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVPToken>;
    deployContract(
      name: "IWeb2JsonVerification",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWeb2JsonVerification>;
    deployContract(
      name: "IWNat",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWNat>;
    deployContract(
      name: "IWNatDelegationFee",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWNatDelegationFee>;
    deployContract(
      name: "IXrplProviderWalletsFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IXrplProviderWalletsFacet>;
    deployContract(
      name: "IXRPPaymentNonexistenceVerification",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IXRPPaymentNonexistenceVerification>;
    deployContract(
      name: "IXRPPaymentVerification",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IXRPPaymentVerification>;
    deployContract(
      name: "ProtocolsV2Interface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProtocolsV2Interface>;
    deployContract(
      name: "RandomNumberV2Interface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RandomNumberV2Interface>;
    deployContract(
      name: "RewardsV2Interface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RewardsV2Interface>;
    deployContract(
      name: "TestFtsoV2Interface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestFtsoV2Interface>;
    deployContract(
      name: "IICleanable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IICleanable>;
    deployContract(
      name: "IIGovernanceVotePower",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIGovernanceVotePower>;
    deployContract(
      name: "IIVPContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIVPContract>;
    deployContract(
      name: "IIVPToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIVPToken>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "IBeacon",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBeacon>;
    deployContract(
      name: "ERC1155",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1155>;
    deployContract(
      name: "IERC1155MetadataURI",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155MetadataURI>;
    deployContract(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155>;
    deployContract(
      name: "IERC1155Receiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Receiver>;
    deployContract(
      name: "ERC1155Holder",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1155Holder>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "IOutcomeResolver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IOutcomeResolver>;
    deployContract(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "PolycastOracleMinter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolycastOracleMinter>;
    deployContract(
      name: "PolycastOracleMinterFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolycastOracleMinterFactory>;
    deployContract(
      name: "PolymarketPriceOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolymarketPriceOracle>;
    deployContract(
      name: "PolycastAMM",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolycastAMM>;
    deployContract(
      name: "PolycastAMMFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolycastAMMFactory>;
    deployContract(
      name: "PolycastMarket",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolycastMarket>;
    deployContract(
      name: "PolycastMarketFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolycastMarketFactory>;
    deployContract(
      name: "FdcWeb2JsonResolver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FdcWeb2JsonResolver>;
    deployContract(
      name: "FtsoPriceResolver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FtsoPriceResolver>;
    deployContract(
      name: "ManualResolver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ManualResolver>;

    deployContract(
      name: "IDiamond",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDiamond>;
    deployContract(
      name: "IDiamondCut",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDiamondCut>;
    deployContract(
      name: "IDiamondLoupe",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDiamondLoupe>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "IERC173",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC173>;
    deployContract(
      name: "IIFtso",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIFtso>;
    deployContract(
      name: "FtsoV2Interface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FtsoV2Interface>;
    deployContract(
      name: "IFtsoGenesis",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoGenesis>;
    deployContract(
      name: "IFtsoManagerGenesis",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoManagerGenesis>;
    deployContract(
      name: "IFtsoRegistryGenesis",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoRegistryGenesis>;
    deployContract(
      name: "IAddressValidityVerification",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAddressValidityVerification>;
    deployContract(
      name: "IAgentAlwaysAllowedMinters",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentAlwaysAllowedMinters>;
    deployContract(
      name: "IAgentPing",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentPing>;
    deployContract(
      name: "IAgentVaultsFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentVaultsFacet>;
    deployContract(
      name: "IAssetManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAssetManager>;
    deployContract(
      name: "IAssetManagerController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAssetManagerController>;
    deployContract(
      name: "IAssetManagerEvents",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAssetManagerEvents>;
    deployContract(
      name: "IBalanceDecreasingTransactionVerification",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBalanceDecreasingTransactionVerification>;
    deployContract(
      name: "IClaimSetupManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IClaimSetupManager>;
    deployContract(
      name: "IConfirmedBlockHeightExistsVerification",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IConfirmedBlockHeightExistsVerification>;
    deployContract(
      name: "ICoreVaultClient",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICoreVaultClient>;
    deployContract(
      name: "ICoreVaultClientSettings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICoreVaultClientSettings>;
    deployContract(
      name: "IDelegationAccount",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDelegationAccount>;
    deployContract(
      name: "IDirectMinting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDirectMinting>;
    deployContract(
      name: "IDirectMintingSettings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDirectMintingSettings>;
    deployContract(
      name: "IEntityManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEntityManager>;
    deployContract(
      name: "IEVMTransactionVerification",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEVMTransactionVerification>;
    deployContract(
      name: "IExecutorsFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IExecutorsFacet>;
    deployContract(
      name: "IFastUpdateIncentiveManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFastUpdateIncentiveManager>;
    deployContract(
      name: "IFastUpdater",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFastUpdater>;
    deployContract(
      name: "IFastUpdatesConfiguration",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFastUpdatesConfiguration>;
    deployContract(
      name: "IFdcHub",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFdcHub>;
    deployContract(
      name: "IFdcInflationConfigurations",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFdcInflationConfigurations>;
    deployContract(
      name: "IFdcRequestFeeConfigurations",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFdcRequestFeeConfigurations>;
    deployContract(
      name: "IFdcVerification",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFdcVerification>;
    deployContract(
      name: "IFeeCalculator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFeeCalculator>;
    deployContract(
      name: "IFlareAssetRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlareAssetRegistry>;
    deployContract(
      name: "IFlareContractRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlareContractRegistry>;
    deployContract(
      name: "IFlareSystemsCalculator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlareSystemsCalculator>;
    deployContract(
      name: "IFlareSystemsManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlareSystemsManager>;
    deployContract(
      name: "IFtso",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtso>;
    deployContract(
      name: "IFtsoFeedDecimals",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoFeedDecimals>;
    deployContract(
      name: "IFtsoFeedIdConverter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoFeedIdConverter>;
    deployContract(
      name: "IFtsoFeedPublisher",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoFeedPublisher>;
    deployContract(
      name: "IFtsoInflationConfigurations",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoInflationConfigurations>;
    deployContract(
      name: "IFtsoManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoManager>;
    deployContract(
      name: "IFtsoRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoRegistry>;
    deployContract(
      name: "IFtsoRewardManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoRewardManager>;
    deployContract(
      name: "IFtsoRewardOffersManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFtsoRewardOffersManager>;
    deployContract(
      name: "IGenericRewardManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGenericRewardManager>;
    deployContract(
      name: "IGovernanceSettings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGovernanceSettings>;
    deployContract(
      name: "IGovernanceVotePower",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGovernanceVotePower>;
    deployContract(
      name: "IIncreaseManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIncreaseManager>;
    deployContract(
      name: "IInstructionFeesFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInstructionFeesFacet>;
    deployContract(
      name: "IInstructionsFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInstructionsFacet>;
    deployContract(
      name: "IMasterAccountController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMasterAccountController>;
    deployContract(
      name: "IMemoInstructionsFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMemoInstructionsFacet>;
    deployContract(
      name: "IPauseFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPauseFacet>;
    deployContract(
      name: "IPaymentProofsFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymentProofsFacet>;
    deployContract(
      name: "IPaymentVerification",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymentVerification>;
    deployContract(
      name: "IPChainStakeMirror",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPChainStakeMirror>;
    deployContract(
      name: "IPChainVotePower",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPChainVotePower>;
    deployContract(
      name: "IPersonalAccountsFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPersonalAccountsFacet>;
    deployContract(
      name: "IPriceSubmitter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPriceSubmitter>;
    deployContract(
      name: "IRandomProvider",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRandomProvider>;
    deployContract(
      name: "IReaderFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReaderFacet>;
    deployContract(
      name: "IRedeemExtended",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRedeemExtended>;
    deployContract(
      name: "IRedeemExtendedSettings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRedeemExtendedSettings>;
    deployContract(
      name: "IRedemptionTimeExtension",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRedemptionTimeExtension>;
    deployContract(
      name: "IReferencedPaymentNonexistenceVerification",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReferencedPaymentNonexistenceVerification>;
    deployContract(
      name: "IRelay",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRelay>;
    deployContract(
      name: "IRewardManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRewardManager>;
    deployContract(
      name: "ISubmission",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISubmission>;
    deployContract(
      name: "ITimelockFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITimelockFacet>;
    deployContract(
      name: "IVaultsFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVaultsFacet>;
    deployContract(
      name: "IVoterRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVoterRegistry>;
    deployContract(
      name: "IVoterWhitelister",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVoterWhitelister>;
    deployContract(
      name: "IVPContractEvents",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVPContractEvents>;
    deployContract(
      name: "IVPToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVPToken>;
    deployContract(
      name: "IWeb2JsonVerification",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWeb2JsonVerification>;
    deployContract(
      name: "IWNat",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWNat>;
    deployContract(
      name: "IWNatDelegationFee",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWNatDelegationFee>;
    deployContract(
      name: "IXrplProviderWalletsFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IXrplProviderWalletsFacet>;
    deployContract(
      name: "IXRPPaymentNonexistenceVerification",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IXRPPaymentNonexistenceVerification>;
    deployContract(
      name: "IXRPPaymentVerification",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IXRPPaymentVerification>;
    deployContract(
      name: "ProtocolsV2Interface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProtocolsV2Interface>;
    deployContract(
      name: "RandomNumberV2Interface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RandomNumberV2Interface>;
    deployContract(
      name: "RewardsV2Interface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RewardsV2Interface>;
    deployContract(
      name: "TestFtsoV2Interface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestFtsoV2Interface>;
    deployContract(
      name: "IICleanable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IICleanable>;
    deployContract(
      name: "IIGovernanceVotePower",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIGovernanceVotePower>;
    deployContract(
      name: "IIVPContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIVPContract>;
    deployContract(
      name: "IIVPToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIVPToken>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1363",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "IBeacon",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBeacon>;
    deployContract(
      name: "ERC1155",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1155>;
    deployContract(
      name: "IERC1155MetadataURI",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155MetadataURI>;
    deployContract(
      name: "IERC1155",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155>;
    deployContract(
      name: "IERC1155Receiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Receiver>;
    deployContract(
      name: "ERC1155Holder",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1155Holder>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "IOutcomeResolver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IOutcomeResolver>;
    deployContract(
      name: "MockERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "PolycastOracleMinter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolycastOracleMinter>;
    deployContract(
      name: "PolycastOracleMinterFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolycastOracleMinterFactory>;
    deployContract(
      name: "PolymarketPriceOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolymarketPriceOracle>;
    deployContract(
      name: "PolycastAMM",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolycastAMM>;
    deployContract(
      name: "PolycastAMMFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolycastAMMFactory>;
    deployContract(
      name: "PolycastMarket",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolycastMarket>;
    deployContract(
      name: "PolycastMarketFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolycastMarketFactory>;
    deployContract(
      name: "FdcWeb2JsonResolver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FdcWeb2JsonResolver>;
    deployContract(
      name: "FtsoPriceResolver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FtsoPriceResolver>;
    deployContract(
      name: "ManualResolver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ManualResolver>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
