/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IOutcomeResolverInterface extends Interface {
  getFunction(nameOrSignature: "getOutcome" | "isResolved"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OutcomeResolved"): EventFragment;

  encodeFunctionData(
    functionFragment: "getOutcome",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isResolved",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getOutcome", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isResolved", data: BytesLike): Result;
}

export namespace OutcomeResolvedEvent {
  export type InputTuple = [marketId: BytesLike, outcome: BigNumberish];
  export type OutputTuple = [marketId: string, outcome: bigint];
  export interface OutputObject {
    marketId: string;
    outcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IOutcomeResolver extends BaseContract {
  connect(runner?: ContractRunner | null): IOutcomeResolver;
  waitForDeployment(): Promise<this>;

  interface: IOutcomeResolverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getOutcome: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  isResolved: TypedContractMethod<[marketId: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getOutcome"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isResolved"
  ): TypedContractMethod<[marketId: BytesLike], [boolean], "view">;

  getEvent(
    key: "OutcomeResolved"
  ): TypedContractEvent<
    OutcomeResolvedEvent.InputTuple,
    OutcomeResolvedEvent.OutputTuple,
    OutcomeResolvedEvent.OutputObject
  >;

  filters: {
    "OutcomeResolved(bytes32,uint8)": TypedContractEvent<
      OutcomeResolvedEvent.InputTuple,
      OutcomeResolvedEvent.OutputTuple,
      OutcomeResolvedEvent.OutputObject
    >;
    OutcomeResolved: TypedContractEvent<
      OutcomeResolvedEvent.InputTuple,
      OutcomeResolvedEvent.OutputTuple,
      OutcomeResolvedEvent.OutputObject
    >;
  };
}
