/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IAgentAlwaysAllowedMintersInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAlwaysAllowedMinterForAgent"
      | "alwaysAllowedMintersForAgent"
      | "removeAlwaysAllowedMinterForAgent"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addAlwaysAllowedMinterForAgent",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "alwaysAllowedMintersForAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAlwaysAllowedMinterForAgent",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAlwaysAllowedMinterForAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "alwaysAllowedMintersForAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAlwaysAllowedMinterForAgent",
    data: BytesLike
  ): Result;
}

export interface IAgentAlwaysAllowedMinters extends BaseContract {
  connect(runner?: ContractRunner | null): IAgentAlwaysAllowedMinters;
  waitForDeployment(): Promise<this>;

  interface: IAgentAlwaysAllowedMintersInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAlwaysAllowedMinterForAgent: TypedContractMethod<
    [_agentVault: AddressLike, _minter: AddressLike],
    [void],
    "nonpayable"
  >;

  alwaysAllowedMintersForAgent: TypedContractMethod<
    [_agentVault: AddressLike],
    [string[]],
    "view"
  >;

  removeAlwaysAllowedMinterForAgent: TypedContractMethod<
    [_agentVault: AddressLike, _minter: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAlwaysAllowedMinterForAgent"
  ): TypedContractMethod<
    [_agentVault: AddressLike, _minter: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "alwaysAllowedMintersForAgent"
  ): TypedContractMethod<[_agentVault: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "removeAlwaysAllowedMinterForAgent"
  ): TypedContractMethod<
    [_agentVault: AddressLike, _minter: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
