/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IAgentVaultsFacetInterface extends Interface {
  getFunction(nameOrSignature: "getAgentVaults"): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AgentVaultAdded" | "AgentVaultRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAgentVaults",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getAgentVaults",
    data: BytesLike
  ): Result;
}

export namespace AgentVaultAddedEvent {
  export type InputTuple = [
    agentVaultId: BigNumberish,
    agentVaultAddress: AddressLike
  ];
  export type OutputTuple = [agentVaultId: bigint, agentVaultAddress: string];
  export interface OutputObject {
    agentVaultId: bigint;
    agentVaultAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentVaultRemovedEvent {
  export type InputTuple = [
    agentVaultId: BigNumberish,
    agentVaultAddress: AddressLike
  ];
  export type OutputTuple = [agentVaultId: bigint, agentVaultAddress: string];
  export interface OutputObject {
    agentVaultId: bigint;
    agentVaultAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAgentVaultsFacet extends BaseContract {
  connect(runner?: ContractRunner | null): IAgentVaultsFacet;
  waitForDeployment(): Promise<this>;

  interface: IAgentVaultsFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAgentVaults: TypedContractMethod<
    [],
    [
      [bigint[], string[]] & {
        _agentVaultIds: bigint[];
        _agentVaultAddresses: string[];
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAgentVaults"
  ): TypedContractMethod<
    [],
    [
      [bigint[], string[]] & {
        _agentVaultIds: bigint[];
        _agentVaultAddresses: string[];
      }
    ],
    "view"
  >;

  getEvent(
    key: "AgentVaultAdded"
  ): TypedContractEvent<
    AgentVaultAddedEvent.InputTuple,
    AgentVaultAddedEvent.OutputTuple,
    AgentVaultAddedEvent.OutputObject
  >;
  getEvent(
    key: "AgentVaultRemoved"
  ): TypedContractEvent<
    AgentVaultRemovedEvent.InputTuple,
    AgentVaultRemovedEvent.OutputTuple,
    AgentVaultRemovedEvent.OutputObject
  >;

  filters: {
    "AgentVaultAdded(uint256,address)": TypedContractEvent<
      AgentVaultAddedEvent.InputTuple,
      AgentVaultAddedEvent.OutputTuple,
      AgentVaultAddedEvent.OutputObject
    >;
    AgentVaultAdded: TypedContractEvent<
      AgentVaultAddedEvent.InputTuple,
      AgentVaultAddedEvent.OutputTuple,
      AgentVaultAddedEvent.OutputObject
    >;

    "AgentVaultRemoved(uint256,address)": TypedContractEvent<
      AgentVaultRemovedEvent.InputTuple,
      AgentVaultRemovedEvent.OutputTuple,
      AgentVaultRemovedEvent.OutputObject
    >;
    AgentVaultRemoved: TypedContractEvent<
      AgentVaultRemovedEvent.InputTuple,
      AgentVaultRemovedEvent.OutputTuple,
      AgentVaultRemovedEvent.OutputObject
    >;
  };
}
