/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IDirectMintingSettingsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getDirectMintingDailyLimitUBA"
      | "getDirectMintingDailyLimiterState"
      | "getDirectMintingExecutorFeeUBA"
      | "getDirectMintingFeeBIPS"
      | "getDirectMintingFeeReceiver"
      | "getDirectMintingHourlyLimitUBA"
      | "getDirectMintingHourlyLimiterState"
      | "getDirectMintingLargeMintingDelaySeconds"
      | "getDirectMintingLargeMintingThresholdUBA"
      | "getDirectMintingMinimumFeeUBA"
      | "getDirectMintingOthersCanExecuteAfterSeconds"
      | "getDirectMintingsUnblockUntilTimestamp"
      | "getMintingTagManager"
      | "getSmartAccountManager"
      | "setDirectMintingDailyLimitUBA"
      | "setDirectMintingExecutorFee"
      | "setDirectMintingFee"
      | "setDirectMintingFeeReceiver"
      | "setDirectMintingHourlyLimitUBA"
      | "setDirectMintingLargeMintingThrottling"
      | "setDirectMintingOthersCanExecuteAfterSeconds"
      | "setMintingTagManager"
      | "setSmartAccountManager"
      | "unblockDirectMintingsUntil"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getDirectMintingDailyLimitUBA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingDailyLimiterState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingExecutorFeeUBA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingFeeBIPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingFeeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingHourlyLimitUBA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingHourlyLimiterState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingLargeMintingDelaySeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingLargeMintingThresholdUBA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingMinimumFeeUBA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingOthersCanExecuteAfterSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingsUnblockUntilTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMintingTagManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSmartAccountManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDirectMintingDailyLimitUBA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDirectMintingExecutorFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDirectMintingFee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDirectMintingFeeReceiver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDirectMintingHourlyLimitUBA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDirectMintingLargeMintingThrottling",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDirectMintingOthersCanExecuteAfterSeconds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMintingTagManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSmartAccountManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unblockDirectMintingsUntil",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getDirectMintingDailyLimitUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingDailyLimiterState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingExecutorFeeUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingFeeBIPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingHourlyLimitUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingHourlyLimiterState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingLargeMintingDelaySeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingLargeMintingThresholdUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingMinimumFeeUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingOthersCanExecuteAfterSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingsUnblockUntilTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMintingTagManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSmartAccountManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDirectMintingDailyLimitUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDirectMintingExecutorFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDirectMintingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDirectMintingFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDirectMintingHourlyLimitUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDirectMintingLargeMintingThrottling",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDirectMintingOthersCanExecuteAfterSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMintingTagManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSmartAccountManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unblockDirectMintingsUntil",
    data: BytesLike
  ): Result;
}

export interface IDirectMintingSettings extends BaseContract {
  connect(runner?: ContractRunner | null): IDirectMintingSettings;
  waitForDeployment(): Promise<this>;

  interface: IDirectMintingSettingsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getDirectMintingDailyLimitUBA: TypedContractMethod<[], [bigint], "view">;

  getDirectMintingDailyLimiterState: TypedContractMethod<
    [],
    [
      [bigint, bigint] & {
        _windowStartTimestamp: bigint;
        _mintedInCurrentWindow: bigint;
      }
    ],
    "view"
  >;

  getDirectMintingExecutorFeeUBA: TypedContractMethod<[], [bigint], "view">;

  getDirectMintingFeeBIPS: TypedContractMethod<[], [bigint], "view">;

  getDirectMintingFeeReceiver: TypedContractMethod<[], [string], "view">;

  getDirectMintingHourlyLimitUBA: TypedContractMethod<[], [bigint], "view">;

  getDirectMintingHourlyLimiterState: TypedContractMethod<
    [],
    [
      [bigint, bigint] & {
        _windowStartTimestamp: bigint;
        _mintedInCurrentWindow: bigint;
      }
    ],
    "view"
  >;

  getDirectMintingLargeMintingDelaySeconds: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  getDirectMintingLargeMintingThresholdUBA: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  getDirectMintingMinimumFeeUBA: TypedContractMethod<[], [bigint], "view">;

  getDirectMintingOthersCanExecuteAfterSeconds: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  getDirectMintingsUnblockUntilTimestamp: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  getMintingTagManager: TypedContractMethod<[], [string], "view">;

  getSmartAccountManager: TypedContractMethod<[], [string], "view">;

  setDirectMintingDailyLimitUBA: TypedContractMethod<
    [_dailyLimitUBA: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDirectMintingExecutorFee: TypedContractMethod<
    [_executorFeeUBA: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDirectMintingFee: TypedContractMethod<
    [_mintingFeeBIPS: BigNumberish, _minimumMintingFeeUBA: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDirectMintingFeeReceiver: TypedContractMethod<
    [_mintingFeeReceiver: AddressLike],
    [void],
    "nonpayable"
  >;

  setDirectMintingHourlyLimitUBA: TypedContractMethod<
    [_hourlyLimitUBA: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDirectMintingLargeMintingThrottling: TypedContractMethod<
    [
      _largeMintingThresholdUBA: BigNumberish,
      _largeMintingDelaySeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setDirectMintingOthersCanExecuteAfterSeconds: TypedContractMethod<
    [_seconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMintingTagManager: TypedContractMethod<
    [_mintingTagManager: AddressLike],
    [void],
    "nonpayable"
  >;

  setSmartAccountManager: TypedContractMethod<
    [_smartAccountManager: AddressLike],
    [void],
    "nonpayable"
  >;

  unblockDirectMintingsUntil: TypedContractMethod<
    [_timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getDirectMintingDailyLimitUBA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingDailyLimiterState"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint] & {
        _windowStartTimestamp: bigint;
        _mintedInCurrentWindow: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDirectMintingExecutorFeeUBA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingFeeBIPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingFeeReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingHourlyLimitUBA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingHourlyLimiterState"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint] & {
        _windowStartTimestamp: bigint;
        _mintedInCurrentWindow: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDirectMintingLargeMintingDelaySeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingLargeMintingThresholdUBA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingMinimumFeeUBA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingOthersCanExecuteAfterSeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingsUnblockUntilTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMintingTagManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSmartAccountManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setDirectMintingDailyLimitUBA"
  ): TypedContractMethod<[_dailyLimitUBA: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDirectMintingExecutorFee"
  ): TypedContractMethod<[_executorFeeUBA: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDirectMintingFee"
  ): TypedContractMethod<
    [_mintingFeeBIPS: BigNumberish, _minimumMintingFeeUBA: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDirectMintingFeeReceiver"
  ): TypedContractMethod<
    [_mintingFeeReceiver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDirectMintingHourlyLimitUBA"
  ): TypedContractMethod<[_hourlyLimitUBA: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDirectMintingLargeMintingThrottling"
  ): TypedContractMethod<
    [
      _largeMintingThresholdUBA: BigNumberish,
      _largeMintingDelaySeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDirectMintingOthersCanExecuteAfterSeconds"
  ): TypedContractMethod<[_seconds: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMintingTagManager"
  ): TypedContractMethod<
    [_mintingTagManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSmartAccountManager"
  ): TypedContractMethod<
    [_smartAccountManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unblockDirectMintingsUntil"
  ): TypedContractMethod<[_timestamp: BigNumberish], [void], "nonpayable">;

  filters: {};
}
