/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IXRPPayment {
  export type RequestBodyStruct = {
    transactionId: BytesLike;
    proofOwner: AddressLike;
  };

  export type RequestBodyStructOutput = [
    transactionId: string,
    proofOwner: string
  ] & { transactionId: string; proofOwner: string };

  export type ResponseBodyStruct = {
    blockNumber: BigNumberish;
    blockTimestamp: BigNumberish;
    sourceAddress: string;
    sourceAddressHash: BytesLike;
    receivingAddressHash: BytesLike;
    intendedReceivingAddressHash: BytesLike;
    spentAmount: BigNumberish;
    intendedSpentAmount: BigNumberish;
    receivedAmount: BigNumberish;
    intendedReceivedAmount: BigNumberish;
    hasMemoData: boolean;
    firstMemoData: BytesLike;
    hasDestinationTag: boolean;
    destinationTag: BigNumberish;
    status: BigNumberish;
  };

  export type ResponseBodyStructOutput = [
    blockNumber: bigint,
    blockTimestamp: bigint,
    sourceAddress: string,
    sourceAddressHash: string,
    receivingAddressHash: string,
    intendedReceivingAddressHash: string,
    spentAmount: bigint,
    intendedSpentAmount: bigint,
    receivedAmount: bigint,
    intendedReceivedAmount: bigint,
    hasMemoData: boolean,
    firstMemoData: string,
    hasDestinationTag: boolean,
    destinationTag: bigint,
    status: bigint
  ] & {
    blockNumber: bigint;
    blockTimestamp: bigint;
    sourceAddress: string;
    sourceAddressHash: string;
    receivingAddressHash: string;
    intendedReceivingAddressHash: string;
    spentAmount: bigint;
    intendedSpentAmount: bigint;
    receivedAmount: bigint;
    intendedReceivedAmount: bigint;
    hasMemoData: boolean;
    firstMemoData: string;
    hasDestinationTag: boolean;
    destinationTag: bigint;
    status: bigint;
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IXRPPayment.RequestBodyStruct;
    responseBody: IXRPPayment.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IXRPPayment.RequestBodyStructOutput,
    responseBody: IXRPPayment.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IXRPPayment.RequestBodyStructOutput;
    responseBody: IXRPPayment.ResponseBodyStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    data: IXRPPayment.ResponseStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    data: IXRPPayment.ResponseStructOutput
  ] & { merkleProof: string[]; data: IXRPPayment.ResponseStructOutput };
}

export interface IDirectMintingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "directMintingDelayState"
      | "directMintingPaymentAddress"
      | "executeDirectMinting"
      | "executeDirectMintingWithData"
      | "markUnblockedDirectMintingAllowed"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DirectMintingDelayed"
      | "DirectMintingExecuted"
      | "DirectMintingExecutedToSmartAccount"
      | "DirectMintingPaymentTooSmallForFee"
      | "DirectMintingsUnblocked"
      | "LargeDirectMintingDelayed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "directMintingDelayState",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "directMintingPaymentAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeDirectMinting",
    values: [IXRPPayment.ProofStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "executeDirectMintingWithData",
    values: [IXRPPayment.ProofStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markUnblockedDirectMintingAllowed",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "directMintingDelayState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "directMintingPaymentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeDirectMinting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeDirectMintingWithData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markUnblockedDirectMintingAllowed",
    data: BytesLike
  ): Result;
}

export namespace DirectMintingDelayedEvent {
  export type InputTuple = [
    transactionId: BytesLike,
    amount: BigNumberish,
    executionAllowedAt: BigNumberish
  ];
  export type OutputTuple = [
    transactionId: string,
    amount: bigint,
    executionAllowedAt: bigint
  ];
  export interface OutputObject {
    transactionId: string;
    amount: bigint;
    executionAllowedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DirectMintingExecutedEvent {
  export type InputTuple = [
    transactionId: BytesLike,
    targetAddress: AddressLike,
    executor: AddressLike,
    mintedAmountUBA: BigNumberish,
    mintingFeeUBA: BigNumberish,
    executorFeeUBA: BigNumberish
  ];
  export type OutputTuple = [
    transactionId: string,
    targetAddress: string,
    executor: string,
    mintedAmountUBA: bigint,
    mintingFeeUBA: bigint,
    executorFeeUBA: bigint
  ];
  export interface OutputObject {
    transactionId: string;
    targetAddress: string;
    executor: string;
    mintedAmountUBA: bigint;
    mintingFeeUBA: bigint;
    executorFeeUBA: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DirectMintingExecutedToSmartAccountEvent {
  export type InputTuple = [
    transactionId: BytesLike,
    sourceAddress: string,
    executor: AddressLike,
    mintedAmountUBA: BigNumberish,
    mintingFeeUBA: BigNumberish,
    memoData: BytesLike
  ];
  export type OutputTuple = [
    transactionId: string,
    sourceAddress: string,
    executor: string,
    mintedAmountUBA: bigint,
    mintingFeeUBA: bigint,
    memoData: string
  ];
  export interface OutputObject {
    transactionId: string;
    sourceAddress: string;
    executor: string;
    mintedAmountUBA: bigint;
    mintingFeeUBA: bigint;
    memoData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DirectMintingPaymentTooSmallForFeeEvent {
  export type InputTuple = [
    transactionId: BytesLike,
    receivedAmountUBA: BigNumberish,
    minimumMintingFeeUBA: BigNumberish
  ];
  export type OutputTuple = [
    transactionId: string,
    receivedAmountUBA: bigint,
    minimumMintingFeeUBA: bigint
  ];
  export interface OutputObject {
    transactionId: string;
    receivedAmountUBA: bigint;
    minimumMintingFeeUBA: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DirectMintingsUnblockedEvent {
  export type InputTuple = [startedUntilTimestamp: BigNumberish];
  export type OutputTuple = [startedUntilTimestamp: bigint];
  export interface OutputObject {
    startedUntilTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LargeDirectMintingDelayedEvent {
  export type InputTuple = [
    transactionId: BytesLike,
    amount: BigNumberish,
    executionAllowedAt: BigNumberish
  ];
  export type OutputTuple = [
    transactionId: string,
    amount: bigint,
    executionAllowedAt: bigint
  ];
  export interface OutputObject {
    transactionId: string;
    amount: bigint;
    executionAllowedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDirectMinting extends BaseContract {
  connect(runner?: ContractRunner | null): IDirectMinting;
  waitForDeployment(): Promise<this>;

  interface: IDirectMintingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  directMintingDelayState: TypedContractMethod<
    [_transactionId: BytesLike],
    [
      [bigint, bigint, bigint] & {
        _delayState: bigint;
        _allowedAt: bigint;
        _startedAt: bigint;
      }
    ],
    "view"
  >;

  directMintingPaymentAddress: TypedContractMethod<[], [string], "view">;

  executeDirectMinting: TypedContractMethod<
    [_payment: IXRPPayment.ProofStruct],
    [void],
    "payable"
  >;

  executeDirectMintingWithData: TypedContractMethod<
    [_payment: IXRPPayment.ProofStruct, _data: BytesLike],
    [void],
    "payable"
  >;

  markUnblockedDirectMintingAllowed: TypedContractMethod<
    [_transactionId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "directMintingDelayState"
  ): TypedContractMethod<
    [_transactionId: BytesLike],
    [
      [bigint, bigint, bigint] & {
        _delayState: bigint;
        _allowedAt: bigint;
        _startedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "directMintingPaymentAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeDirectMinting"
  ): TypedContractMethod<
    [_payment: IXRPPayment.ProofStruct],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executeDirectMintingWithData"
  ): TypedContractMethod<
    [_payment: IXRPPayment.ProofStruct, _data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "markUnblockedDirectMintingAllowed"
  ): TypedContractMethod<[_transactionId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "DirectMintingDelayed"
  ): TypedContractEvent<
    DirectMintingDelayedEvent.InputTuple,
    DirectMintingDelayedEvent.OutputTuple,
    DirectMintingDelayedEvent.OutputObject
  >;
  getEvent(
    key: "DirectMintingExecuted"
  ): TypedContractEvent<
    DirectMintingExecutedEvent.InputTuple,
    DirectMintingExecutedEvent.OutputTuple,
    DirectMintingExecutedEvent.OutputObject
  >;
  getEvent(
    key: "DirectMintingExecutedToSmartAccount"
  ): TypedContractEvent<
    DirectMintingExecutedToSmartAccountEvent.InputTuple,
    DirectMintingExecutedToSmartAccountEvent.OutputTuple,
    DirectMintingExecutedToSmartAccountEvent.OutputObject
  >;
  getEvent(
    key: "DirectMintingPaymentTooSmallForFee"
  ): TypedContractEvent<
    DirectMintingPaymentTooSmallForFeeEvent.InputTuple,
    DirectMintingPaymentTooSmallForFeeEvent.OutputTuple,
    DirectMintingPaymentTooSmallForFeeEvent.OutputObject
  >;
  getEvent(
    key: "DirectMintingsUnblocked"
  ): TypedContractEvent<
    DirectMintingsUnblockedEvent.InputTuple,
    DirectMintingsUnblockedEvent.OutputTuple,
    DirectMintingsUnblockedEvent.OutputObject
  >;
  getEvent(
    key: "LargeDirectMintingDelayed"
  ): TypedContractEvent<
    LargeDirectMintingDelayedEvent.InputTuple,
    LargeDirectMintingDelayedEvent.OutputTuple,
    LargeDirectMintingDelayedEvent.OutputObject
  >;

  filters: {
    "DirectMintingDelayed(bytes32,uint256,uint256)": TypedContractEvent<
      DirectMintingDelayedEvent.InputTuple,
      DirectMintingDelayedEvent.OutputTuple,
      DirectMintingDelayedEvent.OutputObject
    >;
    DirectMintingDelayed: TypedContractEvent<
      DirectMintingDelayedEvent.InputTuple,
      DirectMintingDelayedEvent.OutputTuple,
      DirectMintingDelayedEvent.OutputObject
    >;

    "DirectMintingExecuted(bytes32,address,address,uint256,uint256,uint256)": TypedContractEvent<
      DirectMintingExecutedEvent.InputTuple,
      DirectMintingExecutedEvent.OutputTuple,
      DirectMintingExecutedEvent.OutputObject
    >;
    DirectMintingExecuted: TypedContractEvent<
      DirectMintingExecutedEvent.InputTuple,
      DirectMintingExecutedEvent.OutputTuple,
      DirectMintingExecutedEvent.OutputObject
    >;

    "DirectMintingExecutedToSmartAccount(bytes32,string,address,uint256,uint256,bytes)": TypedContractEvent<
      DirectMintingExecutedToSmartAccountEvent.InputTuple,
      DirectMintingExecutedToSmartAccountEvent.OutputTuple,
      DirectMintingExecutedToSmartAccountEvent.OutputObject
    >;
    DirectMintingExecutedToSmartAccount: TypedContractEvent<
      DirectMintingExecutedToSmartAccountEvent.InputTuple,
      DirectMintingExecutedToSmartAccountEvent.OutputTuple,
      DirectMintingExecutedToSmartAccountEvent.OutputObject
    >;

    "DirectMintingPaymentTooSmallForFee(bytes32,uint256,uint256)": TypedContractEvent<
      DirectMintingPaymentTooSmallForFeeEvent.InputTuple,
      DirectMintingPaymentTooSmallForFeeEvent.OutputTuple,
      DirectMintingPaymentTooSmallForFeeEvent.OutputObject
    >;
    DirectMintingPaymentTooSmallForFee: TypedContractEvent<
      DirectMintingPaymentTooSmallForFeeEvent.InputTuple,
      DirectMintingPaymentTooSmallForFeeEvent.OutputTuple,
      DirectMintingPaymentTooSmallForFeeEvent.OutputObject
    >;

    "DirectMintingsUnblocked(uint256)": TypedContractEvent<
      DirectMintingsUnblockedEvent.InputTuple,
      DirectMintingsUnblockedEvent.OutputTuple,
      DirectMintingsUnblockedEvent.OutputObject
    >;
    DirectMintingsUnblocked: TypedContractEvent<
      DirectMintingsUnblockedEvent.InputTuple,
      DirectMintingsUnblockedEvent.OutputTuple,
      DirectMintingsUnblockedEvent.OutputObject
    >;

    "LargeDirectMintingDelayed(bytes32,uint256,uint256)": TypedContractEvent<
      LargeDirectMintingDelayedEvent.InputTuple,
      LargeDirectMintingDelayedEvent.OutputTuple,
      LargeDirectMintingDelayedEvent.OutputObject
    >;
    LargeDirectMintingDelayed: TypedContractEvent<
      LargeDirectMintingDelayedEvent.InputTuple,
      LargeDirectMintingDelayedEvent.OutputTuple,
      LargeDirectMintingDelayedEvent.OutputObject
    >;
  };
}
