/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IExecutorsFacetInterface extends Interface {
  getFunction(nameOrSignature: "getExecutorInfo"): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ExecutorFeeSet" | "ExecutorSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getExecutorInfo",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getExecutorInfo",
    data: BytesLike
  ): Result;
}

export namespace ExecutorFeeSetEvent {
  export type InputTuple = [executorFee: BigNumberish];
  export type OutputTuple = [executorFee: bigint];
  export interface OutputObject {
    executorFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorSetEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IExecutorsFacet extends BaseContract {
  connect(runner?: ContractRunner | null): IExecutorsFacet;
  waitForDeployment(): Promise<this>;

  interface: IExecutorsFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getExecutorInfo: TypedContractMethod<
    [],
    [[string, bigint] & { _executor: string; _executorFee: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getExecutorInfo"
  ): TypedContractMethod<
    [],
    [[string, bigint] & { _executor: string; _executorFee: bigint }],
    "view"
  >;

  getEvent(
    key: "ExecutorFeeSet"
  ): TypedContractEvent<
    ExecutorFeeSetEvent.InputTuple,
    ExecutorFeeSetEvent.OutputTuple,
    ExecutorFeeSetEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorSet"
  ): TypedContractEvent<
    ExecutorSetEvent.InputTuple,
    ExecutorSetEvent.OutputTuple,
    ExecutorSetEvent.OutputObject
  >;

  filters: {
    "ExecutorFeeSet(uint256)": TypedContractEvent<
      ExecutorFeeSetEvent.InputTuple,
      ExecutorFeeSetEvent.OutputTuple,
      ExecutorFeeSetEvent.OutputObject
    >;
    ExecutorFeeSet: TypedContractEvent<
      ExecutorFeeSetEvent.InputTuple,
      ExecutorFeeSetEvent.OutputTuple,
      ExecutorFeeSetEvent.OutputObject
    >;

    "ExecutorSet(address)": TypedContractEvent<
      ExecutorSetEvent.InputTuple,
      ExecutorSetEvent.OutputTuple,
      ExecutorSetEvent.OutputObject
    >;
    ExecutorSet: TypedContractEvent<
      ExecutorSetEvent.InputTuple,
      ExecutorSetEvent.OutputTuple,
      ExecutorSetEvent.OutputObject
    >;
  };
}
