/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IInstructionFeesFacetInterface extends Interface {
  getFunction(
    nameOrSignature: "getDefaultInstructionFee" | "getInstructionFee"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DefaultInstructionFeeSet"
      | "InstructionFeeRemoved"
      | "InstructionFeeSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getDefaultInstructionFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInstructionFee",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getDefaultInstructionFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInstructionFee",
    data: BytesLike
  ): Result;
}

export namespace DefaultInstructionFeeSetEvent {
  export type InputTuple = [defaultInstructionFee: BigNumberish];
  export type OutputTuple = [defaultInstructionFee: bigint];
  export interface OutputObject {
    defaultInstructionFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstructionFeeRemovedEvent {
  export type InputTuple = [instructionId: BigNumberish];
  export type OutputTuple = [instructionId: bigint];
  export interface OutputObject {
    instructionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstructionFeeSetEvent {
  export type InputTuple = [
    instructionId: BigNumberish,
    instructionFee: BigNumberish
  ];
  export type OutputTuple = [instructionId: bigint, instructionFee: bigint];
  export interface OutputObject {
    instructionId: bigint;
    instructionFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IInstructionFeesFacet extends BaseContract {
  connect(runner?: ContractRunner | null): IInstructionFeesFacet;
  waitForDeployment(): Promise<this>;

  interface: IInstructionFeesFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getDefaultInstructionFee: TypedContractMethod<[], [bigint], "view">;

  getInstructionFee: TypedContractMethod<
    [_instructionId: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getDefaultInstructionFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getInstructionFee"
  ): TypedContractMethod<[_instructionId: BigNumberish], [bigint], "view">;

  getEvent(
    key: "DefaultInstructionFeeSet"
  ): TypedContractEvent<
    DefaultInstructionFeeSetEvent.InputTuple,
    DefaultInstructionFeeSetEvent.OutputTuple,
    DefaultInstructionFeeSetEvent.OutputObject
  >;
  getEvent(
    key: "InstructionFeeRemoved"
  ): TypedContractEvent<
    InstructionFeeRemovedEvent.InputTuple,
    InstructionFeeRemovedEvent.OutputTuple,
    InstructionFeeRemovedEvent.OutputObject
  >;
  getEvent(
    key: "InstructionFeeSet"
  ): TypedContractEvent<
    InstructionFeeSetEvent.InputTuple,
    InstructionFeeSetEvent.OutputTuple,
    InstructionFeeSetEvent.OutputObject
  >;

  filters: {
    "DefaultInstructionFeeSet(uint256)": TypedContractEvent<
      DefaultInstructionFeeSetEvent.InputTuple,
      DefaultInstructionFeeSetEvent.OutputTuple,
      DefaultInstructionFeeSetEvent.OutputObject
    >;
    DefaultInstructionFeeSet: TypedContractEvent<
      DefaultInstructionFeeSetEvent.InputTuple,
      DefaultInstructionFeeSetEvent.OutputTuple,
      DefaultInstructionFeeSetEvent.OutputObject
    >;

    "InstructionFeeRemoved(uint256)": TypedContractEvent<
      InstructionFeeRemovedEvent.InputTuple,
      InstructionFeeRemovedEvent.OutputTuple,
      InstructionFeeRemovedEvent.OutputObject
    >;
    InstructionFeeRemoved: TypedContractEvent<
      InstructionFeeRemovedEvent.InputTuple,
      InstructionFeeRemovedEvent.OutputTuple,
      InstructionFeeRemovedEvent.OutputObject
    >;

    "InstructionFeeSet(uint256,uint256)": TypedContractEvent<
      InstructionFeeSetEvent.InputTuple,
      InstructionFeeSetEvent.OutputTuple,
      InstructionFeeSetEvent.OutputObject
    >;
    InstructionFeeSet: TypedContractEvent<
      InstructionFeeSetEvent.InputTuple,
      InstructionFeeSetEvent.OutputTuple,
      InstructionFeeSetEvent.OutputObject
    >;
  };
}
