/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IDiamond {
  export type FacetCutStruct = {
    facetAddress: AddressLike;
    action: BigNumberish;
    functionSelectors: BytesLike[];
  };

  export type FacetCutStructOutput = [
    facetAddress: string,
    action: bigint,
    functionSelectors: string[]
  ] & { facetAddress: string; action: bigint; functionSelectors: string[] };
}

export declare namespace IReaderFacet {
  export type AgentVaultDetailsStruct = {
    agentVaultId: BigNumberish;
    agentVaultAddress: AddressLike;
  };

  export type AgentVaultDetailsStructOutput = [
    agentVaultId: bigint,
    agentVaultAddress: string
  ] & { agentVaultId: bigint; agentVaultAddress: string };

  export type TokenBalanceStruct = {
    token: AddressLike;
    balance: BigNumberish;
  };

  export type TokenBalanceStructOutput = [token: string, balance: bigint] & {
    token: string;
    balance: bigint;
  };

  export type VaultBalanceStruct = {
    vaultId: BigNumberish;
    vaultAddress: AddressLike;
    vaultType: BigNumberish;
    shares: BigNumberish;
    assets: BigNumberish;
  };

  export type VaultBalanceStructOutput = [
    vaultId: bigint,
    vaultAddress: string,
    vaultType: bigint,
    shares: bigint,
    assets: bigint
  ] & {
    vaultId: bigint;
    vaultAddress: string;
    vaultType: bigint;
    shares: bigint;
    assets: bigint;
  };

  export type AccountBalancesStruct = {
    natBalance: BigNumberish;
    wNat: IReaderFacet.TokenBalanceStruct;
    fXrp: IReaderFacet.TokenBalanceStruct;
    vaults: IReaderFacet.VaultBalanceStruct[];
  };

  export type AccountBalancesStructOutput = [
    natBalance: bigint,
    wNat: IReaderFacet.TokenBalanceStructOutput,
    fXrp: IReaderFacet.TokenBalanceStructOutput,
    vaults: IReaderFacet.VaultBalanceStructOutput[]
  ] & {
    natBalance: bigint;
    wNat: IReaderFacet.TokenBalanceStructOutput;
    fXrp: IReaderFacet.TokenBalanceStructOutput;
    vaults: IReaderFacet.VaultBalanceStructOutput[];
  };

  export type VaultDetailsStruct = {
    vaultId: BigNumberish;
    vaultAddress: AddressLike;
    vaultType: BigNumberish;
  };

  export type VaultDetailsStructOutput = [
    vaultId: bigint,
    vaultAddress: string,
    vaultType: bigint
  ] & { vaultId: bigint; vaultAddress: string; vaultType: bigint };
}

export declare namespace IPayment {
  export type RequestBodyStruct = {
    transactionId: BytesLike;
    inUtxo: BigNumberish;
    utxo: BigNumberish;
  };

  export type RequestBodyStructOutput = [
    transactionId: string,
    inUtxo: bigint,
    utxo: bigint
  ] & { transactionId: string; inUtxo: bigint; utxo: bigint };

  export type ResponseBodyStruct = {
    blockNumber: BigNumberish;
    blockTimestamp: BigNumberish;
    sourceAddressHash: BytesLike;
    sourceAddressesRoot: BytesLike;
    receivingAddressHash: BytesLike;
    intendedReceivingAddressHash: BytesLike;
    spentAmount: BigNumberish;
    intendedSpentAmount: BigNumberish;
    receivedAmount: BigNumberish;
    intendedReceivedAmount: BigNumberish;
    standardPaymentReference: BytesLike;
    oneToOne: boolean;
    status: BigNumberish;
  };

  export type ResponseBodyStructOutput = [
    blockNumber: bigint,
    blockTimestamp: bigint,
    sourceAddressHash: string,
    sourceAddressesRoot: string,
    receivingAddressHash: string,
    intendedReceivingAddressHash: string,
    spentAmount: bigint,
    intendedSpentAmount: bigint,
    receivedAmount: bigint,
    intendedReceivedAmount: bigint,
    standardPaymentReference: string,
    oneToOne: boolean,
    status: bigint
  ] & {
    blockNumber: bigint;
    blockTimestamp: bigint;
    sourceAddressHash: string;
    sourceAddressesRoot: string;
    receivingAddressHash: string;
    intendedReceivingAddressHash: string;
    spentAmount: bigint;
    intendedSpentAmount: bigint;
    receivedAmount: bigint;
    intendedReceivedAmount: bigint;
    standardPaymentReference: string;
    oneToOne: boolean;
    status: bigint;
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IPayment.RequestBodyStruct;
    responseBody: IPayment.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IPayment.RequestBodyStructOutput,
    responseBody: IPayment.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IPayment.RequestBodyStructOutput;
    responseBody: IPayment.ResponseBodyStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    data: IPayment.ResponseStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    data: IPayment.ResponseStructOutput
  ] & { merkleProof: string[]; data: IPayment.ResponseStructOutput };
}

export declare namespace IDiamondLoupe {
  export type FacetStruct = {
    facetAddress: AddressLike;
    functionSelectors: BytesLike[];
  };

  export type FacetStructOutput = [
    facetAddress: string,
    functionSelectors: string[]
  ] & { facetAddress: string; functionSelectors: string[] };
}

export interface IMasterAccountControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentVaults"
      | "diamondCut"
      | "executeDepositAfterMinting"
      | "executeInstruction"
      | "executeTimelockedCall"
      | "facetAddress"
      | "facetAddresses"
      | "facetFunctionSelectors"
      | "facets"
      | "getAgentVaults"
      | "getBalances(string)"
      | "getBalances(address)"
      | "getDefaultInstructionFee"
      | "getExecuteTimelockedCallTimestamp"
      | "getExecutor"
      | "getExecutorInfo"
      | "getInstructionFee"
      | "getNonce"
      | "getPausers"
      | "getPaymentProofValidityDurationSeconds"
      | "getPersonalAccount"
      | "getSourceId"
      | "getTimelockDurationSeconds"
      | "getTransactionIdForCollateralReservation"
      | "getUnpausers"
      | "getVaults"
      | "getXrplProviderWallets"
      | "implementation"
      | "isPaused"
      | "isPauser"
      | "isSmartAccount"
      | "isTransactionIdUsed"
      | "isUnpauser"
      | "mintedFAssets"
      | "owner"
      | "pause"
      | "reserveCollateral"
      | "supportsInterface"
      | "transferOwnership"
      | "unpause"
      | "vaults"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentVaultAdded"
      | "AgentVaultRemoved"
      | "Approved"
      | "CallTimelocked"
      | "Claimed"
      | "CollateralReserved"
      | "DefaultInstructionFeeSet"
      | "Deposited"
      | "DiamondCut"
      | "DirectMintingExecuted"
      | "ExecutorFeeSet"
      | "ExecutorRemoved"
      | "ExecutorSet(address)"
      | "ExecutorSet(address,address)"
      | "FXrpRedeemed"
      | "FXrpTransferred"
      | "IgnoreMemoSet"
      | "InstructionExecuted"
      | "InstructionFeeRemoved"
      | "InstructionFeeSet"
      | "NonceIncreased"
      | "OwnershipTransferred"
      | "Paused"
      | "PauserAdded"
      | "PauserRemoved"
      | "PaymentProofValidityDurationSecondsSet"
      | "PersonalAccountCreated"
      | "PersonalAccountImplementationSet"
      | "RedeemRequested"
      | "Redeemed"
      | "ReplacementFeeSet"
      | "TimelockDurationSet"
      | "TimelockedCallCanceled"
      | "TimelockedCallExecuted"
      | "Unpaused"
      | "UnpauserAdded"
      | "UnpauserRemoved"
      | "UserOperationExecuted"
      | "VaultAdded"
      | "WithdrawalClaimed"
      | "XrplProviderWalletAdded"
      | "XrplProviderWalletRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentVaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "diamondCut",
    values: [IDiamond.FacetCutStruct[], AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeDepositAfterMinting",
    values: [BigNumberish, IPayment.ProofStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "executeInstruction",
    values: [IPayment.ProofStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTimelockedCall",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "facetAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "facetAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "facetFunctionSelectors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "facets", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAgentVaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalances(string)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalances(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDefaultInstructionFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExecuteTimelockedCallTimestamp",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutorInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInstructionFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNonce",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPausers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentProofValidityDurationSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPersonalAccount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSourceId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTimelockDurationSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionIdForCollateralReservation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnpausers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getVaults", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getXrplProviderWallets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isPauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSmartAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTransactionIdUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isUnpauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintedFAssets",
    values: [
      BytesLike,
      string,
      BigNumberish,
      BigNumberish,
      BytesLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reserveCollateral",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "vaults", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "agentVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "diamondCut", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeDepositAfterMinting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeInstruction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTimelockedCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "facetAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "facetAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "facetFunctionSelectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "facets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalances(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalances(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDefaultInstructionFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecuteTimelockedCallTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutorInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInstructionFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPausers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentProofValidityDurationSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPersonalAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSourceId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimelockDurationSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionIdForCollateralReservation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnpausers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVaults", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getXrplProviderWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSmartAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTransactionIdUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isUnpauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintedFAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reserveCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;
}

export namespace AgentVaultAddedEvent {
  export type InputTuple = [
    agentVaultId: BigNumberish,
    agentVaultAddress: AddressLike
  ];
  export type OutputTuple = [agentVaultId: bigint, agentVaultAddress: string];
  export interface OutputObject {
    agentVaultId: bigint;
    agentVaultAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentVaultRemovedEvent {
  export type InputTuple = [
    agentVaultId: BigNumberish,
    agentVaultAddress: AddressLike
  ];
  export type OutputTuple = [agentVaultId: bigint, agentVaultAddress: string];
  export interface OutputObject {
    agentVaultId: bigint;
    agentVaultAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovedEvent {
  export type InputTuple = [
    personalAccount: AddressLike,
    fxrp: AddressLike,
    vault: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    personalAccount: string,
    fxrp: string,
    vault: string,
    amount: bigint
  ];
  export interface OutputObject {
    personalAccount: string;
    fxrp: string;
    vault: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CallTimelockedEvent {
  export type InputTuple = [
    encodedCall: BytesLike,
    encodedCallHash: BytesLike,
    allowedAfterTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    encodedCall: string,
    encodedCallHash: string,
    allowedAfterTimestamp: bigint
  ];
  export interface OutputObject {
    encodedCall: string;
    encodedCallHash: string;
    allowedAfterTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    personalAccount: AddressLike,
    vault: AddressLike,
    year: BigNumberish,
    month: BigNumberish,
    day: BigNumberish,
    shares: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    personalAccount: string,
    vault: string,
    year: bigint,
    month: bigint,
    day: bigint,
    shares: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    personalAccount: string;
    vault: string;
    year: bigint;
    month: bigint;
    day: bigint;
    shares: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralReservedEvent {
  export type InputTuple = [
    personalAccount: AddressLike,
    transactionId: BytesLike,
    paymentReference: BytesLike,
    xrplOwner: string,
    collateralReservationId: BigNumberish,
    agentVault: AddressLike,
    lots: BigNumberish,
    executor: AddressLike,
    executorFee: BigNumberish
  ];
  export type OutputTuple = [
    personalAccount: string,
    transactionId: string,
    paymentReference: string,
    xrplOwner: string,
    collateralReservationId: bigint,
    agentVault: string,
    lots: bigint,
    executor: string,
    executorFee: bigint
  ];
  export interface OutputObject {
    personalAccount: string;
    transactionId: string;
    paymentReference: string;
    xrplOwner: string;
    collateralReservationId: bigint;
    agentVault: string;
    lots: bigint;
    executor: string;
    executorFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultInstructionFeeSetEvent {
  export type InputTuple = [defaultInstructionFee: BigNumberish];
  export type OutputTuple = [defaultInstructionFee: bigint];
  export interface OutputObject {
    defaultInstructionFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    personalAccount: AddressLike,
    vault: AddressLike,
    amount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    personalAccount: string,
    vault: string,
    amount: bigint,
    shares: bigint
  ];
  export interface OutputObject {
    personalAccount: string;
    vault: string;
    amount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DiamondCutEvent {
  export type InputTuple = [
    _diamondCut: IDiamond.FacetCutStruct[],
    _init: AddressLike,
    _calldata: BytesLike
  ];
  export type OutputTuple = [
    _diamondCut: IDiamond.FacetCutStructOutput[],
    _init: string,
    _calldata: string
  ];
  export interface OutputObject {
    _diamondCut: IDiamond.FacetCutStructOutput[];
    _init: string;
    _calldata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DirectMintingExecutedEvent {
  export type InputTuple = [
    personalAccount: AddressLike,
    transactionId: BytesLike,
    sourceAddress: string,
    amount: BigNumberish,
    executorFee: BigNumberish,
    executor: AddressLike
  ];
  export type OutputTuple = [
    personalAccount: string,
    transactionId: string,
    sourceAddress: string,
    amount: bigint,
    executorFee: bigint,
    executor: string
  ];
  export interface OutputObject {
    personalAccount: string;
    transactionId: string;
    sourceAddress: string;
    amount: bigint;
    executorFee: bigint;
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorFeeSetEvent {
  export type InputTuple = [executorFee: BigNumberish];
  export type OutputTuple = [executorFee: bigint];
  export interface OutputObject {
    executorFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorRemovedEvent {
  export type InputTuple = [personalAccount: AddressLike];
  export type OutputTuple = [personalAccount: string];
  export interface OutputObject {
    personalAccount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorSet_address_Event {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorSet_address_address_Event {
  export type InputTuple = [
    personalAccount: AddressLike,
    executor: AddressLike
  ];
  export type OutputTuple = [personalAccount: string, executor: string];
  export interface OutputObject {
    personalAccount: string;
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FXrpRedeemedEvent {
  export type InputTuple = [
    personalAccount: AddressLike,
    lots: BigNumberish,
    amount: BigNumberish,
    executor: AddressLike,
    executorFee: BigNumberish
  ];
  export type OutputTuple = [
    personalAccount: string,
    lots: bigint,
    amount: bigint,
    executor: string,
    executorFee: bigint
  ];
  export interface OutputObject {
    personalAccount: string;
    lots: bigint;
    amount: bigint;
    executor: string;
    executorFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FXrpTransferredEvent {
  export type InputTuple = [
    personalAccount: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    personalAccount: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    personalAccount: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IgnoreMemoSetEvent {
  export type InputTuple = [
    personalAccount: AddressLike,
    targetTxId: BytesLike
  ];
  export type OutputTuple = [personalAccount: string, targetTxId: string];
  export interface OutputObject {
    personalAccount: string;
    targetTxId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstructionExecutedEvent {
  export type InputTuple = [
    personalAccount: AddressLike,
    transactionId: BytesLike,
    paymentReference: BytesLike,
    xrplOwner: string,
    instructionId: BigNumberish
  ];
  export type OutputTuple = [
    personalAccount: string,
    transactionId: string,
    paymentReference: string,
    xrplOwner: string,
    instructionId: bigint
  ];
  export interface OutputObject {
    personalAccount: string;
    transactionId: string;
    paymentReference: string;
    xrplOwner: string;
    instructionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstructionFeeRemovedEvent {
  export type InputTuple = [instructionId: BigNumberish];
  export type OutputTuple = [instructionId: bigint];
  export interface OutputObject {
    instructionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstructionFeeSetEvent {
  export type InputTuple = [
    instructionId: BigNumberish,
    instructionFee: BigNumberish
  ];
  export type OutputTuple = [instructionId: bigint, instructionFee: bigint];
  export interface OutputObject {
    instructionId: bigint;
    instructionFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NonceIncreasedEvent {
  export type InputTuple = [
    personalAccount: AddressLike,
    newNonce: BigNumberish
  ];
  export type OutputTuple = [personalAccount: string, newNonce: bigint];
  export interface OutputObject {
    personalAccount: string;
    newNonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauserAddedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauserRemovedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentProofValidityDurationSecondsSetEvent {
  export type InputTuple = [paymentProofValidityDurationSeconds: BigNumberish];
  export type OutputTuple = [paymentProofValidityDurationSeconds: bigint];
  export interface OutputObject {
    paymentProofValidityDurationSeconds: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PersonalAccountCreatedEvent {
  export type InputTuple = [personalAccount: AddressLike, xrplOwner: string];
  export type OutputTuple = [personalAccount: string, xrplOwner: string];
  export interface OutputObject {
    personalAccount: string;
    xrplOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PersonalAccountImplementationSetEvent {
  export type InputTuple = [newImplementation: AddressLike];
  export type OutputTuple = [newImplementation: string];
  export interface OutputObject {
    newImplementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemRequestedEvent {
  export type InputTuple = [
    personalAccount: AddressLike,
    vault: AddressLike,
    shares: BigNumberish,
    claimableEpoch: BigNumberish,
    year: BigNumberish,
    month: BigNumberish,
    day: BigNumberish
  ];
  export type OutputTuple = [
    personalAccount: string,
    vault: string,
    shares: bigint,
    claimableEpoch: bigint,
    year: bigint,
    month: bigint,
    day: bigint
  ];
  export interface OutputObject {
    personalAccount: string;
    vault: string;
    shares: bigint;
    claimableEpoch: bigint;
    year: bigint;
    month: bigint;
    day: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemedEvent {
  export type InputTuple = [
    personalAccount: AddressLike,
    vault: AddressLike,
    shares: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    personalAccount: string,
    vault: string,
    shares: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    personalAccount: string;
    vault: string;
    shares: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReplacementFeeSetEvent {
  export type InputTuple = [
    personalAccount: AddressLike,
    targetTxId: BytesLike,
    newFee: BigNumberish
  ];
  export type OutputTuple = [
    personalAccount: string,
    targetTxId: string,
    newFee: bigint
  ];
  export interface OutputObject {
    personalAccount: string;
    targetTxId: string;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockDurationSetEvent {
  export type InputTuple = [timelockDurationSeconds: BigNumberish];
  export type OutputTuple = [timelockDurationSeconds: bigint];
  export interface OutputObject {
    timelockDurationSeconds: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockedCallCanceledEvent {
  export type InputTuple = [encodedCallHash: BytesLike];
  export type OutputTuple = [encodedCallHash: string];
  export interface OutputObject {
    encodedCallHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockedCallExecutedEvent {
  export type InputTuple = [encodedCallHash: BytesLike];
  export type OutputTuple = [encodedCallHash: string];
  export interface OutputObject {
    encodedCallHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpauserAddedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpauserRemovedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserOperationExecutedEvent {
  export type InputTuple = [personalAccount: AddressLike, nonce: BigNumberish];
  export type OutputTuple = [personalAccount: string, nonce: bigint];
  export interface OutputObject {
    personalAccount: string;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultAddedEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    vaultAddress: AddressLike,
    vaultType: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: bigint,
    vaultAddress: string,
    vaultType: bigint
  ];
  export interface OutputObject {
    vaultId: bigint;
    vaultAddress: string;
    vaultType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalClaimedEvent {
  export type InputTuple = [
    personalAccount: AddressLike,
    vault: AddressLike,
    period: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    personalAccount: string,
    vault: string,
    period: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    personalAccount: string;
    vault: string;
    period: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XrplProviderWalletAddedEvent {
  export type InputTuple = [xrplProviderWallet: string];
  export type OutputTuple = [xrplProviderWallet: string];
  export interface OutputObject {
    xrplProviderWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XrplProviderWalletRemovedEvent {
  export type InputTuple = [xrplProviderWallet: string];
  export type OutputTuple = [xrplProviderWallet: string];
  export interface OutputObject {
    xrplProviderWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IMasterAccountController extends BaseContract {
  connect(runner?: ContractRunner | null): IMasterAccountController;
  waitForDeployment(): Promise<this>;

  interface: IMasterAccountControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentVaults: TypedContractMethod<
    [],
    [IReaderFacet.AgentVaultDetailsStructOutput[]],
    "view"
  >;

  diamondCut: TypedContractMethod<
    [
      _diamondCut: IDiamond.FacetCutStruct[],
      _init: AddressLike,
      _calldata: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  executeDepositAfterMinting: TypedContractMethod<
    [
      _collateralReservationId: BigNumberish,
      _proof: IPayment.ProofStruct,
      _xrplAddress: string
    ],
    [void],
    "nonpayable"
  >;

  executeInstruction: TypedContractMethod<
    [_proof: IPayment.ProofStruct, _xrplAddress: string],
    [void],
    "payable"
  >;

  executeTimelockedCall: TypedContractMethod<
    [_encodedCall: BytesLike],
    [void],
    "nonpayable"
  >;

  facetAddress: TypedContractMethod<
    [_functionSelector: BytesLike],
    [string],
    "view"
  >;

  facetAddresses: TypedContractMethod<[], [string[]], "view">;

  facetFunctionSelectors: TypedContractMethod<
    [_facet: AddressLike],
    [string[]],
    "view"
  >;

  facets: TypedContractMethod<[], [IDiamondLoupe.FacetStructOutput[]], "view">;

  getAgentVaults: TypedContractMethod<
    [],
    [
      [bigint[], string[]] & {
        _agentVaultIds: bigint[];
        _agentVaultAddresses: string[];
      }
    ],
    "view"
  >;

  "getBalances(string)": TypedContractMethod<
    [_xrplOwner: string],
    [IReaderFacet.AccountBalancesStructOutput],
    "view"
  >;

  "getBalances(address)": TypedContractMethod<
    [_account: AddressLike],
    [IReaderFacet.AccountBalancesStructOutput],
    "view"
  >;

  getDefaultInstructionFee: TypedContractMethod<[], [bigint], "view">;

  getExecuteTimelockedCallTimestamp: TypedContractMethod<
    [_encodedCall: BytesLike],
    [bigint],
    "view"
  >;

  getExecutor: TypedContractMethod<
    [_personalAccount: AddressLike],
    [string],
    "view"
  >;

  getExecutorInfo: TypedContractMethod<
    [],
    [[string, bigint] & { _executor: string; _executorFee: bigint }],
    "view"
  >;

  getInstructionFee: TypedContractMethod<
    [_instructionId: BigNumberish],
    [bigint],
    "view"
  >;

  getNonce: TypedContractMethod<
    [_personalAccount: AddressLike],
    [bigint],
    "view"
  >;

  getPausers: TypedContractMethod<[], [string[]], "view">;

  getPaymentProofValidityDurationSeconds: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  getPersonalAccount: TypedContractMethod<
    [_xrplOwner: string],
    [string],
    "view"
  >;

  getSourceId: TypedContractMethod<[], [string], "view">;

  getTimelockDurationSeconds: TypedContractMethod<[], [bigint], "view">;

  getTransactionIdForCollateralReservation: TypedContractMethod<
    [_collateralReservationId: BigNumberish],
    [string],
    "view"
  >;

  getUnpausers: TypedContractMethod<[], [string[]], "view">;

  getVaults: TypedContractMethod<
    [],
    [
      [bigint[], string[], bigint[]] & {
        _vaultIds: bigint[];
        _vaultAddresses: string[];
        _vaultTypes: bigint[];
      }
    ],
    "view"
  >;

  getXrplProviderWallets: TypedContractMethod<[], [string[]], "view">;

  implementation: TypedContractMethod<[], [string], "view">;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  isPauser: TypedContractMethod<[_account: AddressLike], [boolean], "view">;

  isSmartAccount: TypedContractMethod<
    [_address: AddressLike],
    [[boolean, string] & { _isSmartAccount: boolean; _xrplOwner: string }],
    "view"
  >;

  isTransactionIdUsed: TypedContractMethod<
    [_transactionId: BytesLike],
    [boolean],
    "view"
  >;

  isUnpauser: TypedContractMethod<[_account: AddressLike], [boolean], "view">;

  mintedFAssets: TypedContractMethod<
    [
      _transactionId: BytesLike,
      _sourceAddress: string,
      _amount: BigNumberish,
      _underlyingTimestamp: BigNumberish,
      _memoData: BytesLike,
      _executor: AddressLike
    ],
    [void],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  reserveCollateral: TypedContractMethod<
    [
      _xrplAddress: string,
      _paymentReference: BytesLike,
      _transactionId: BytesLike
    ],
    [bigint],
    "payable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  vaults: TypedContractMethod<
    [],
    [IReaderFacet.VaultDetailsStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentVaults"
  ): TypedContractMethod<
    [],
    [IReaderFacet.AgentVaultDetailsStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "diamondCut"
  ): TypedContractMethod<
    [
      _diamondCut: IDiamond.FacetCutStruct[],
      _init: AddressLike,
      _calldata: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeDepositAfterMinting"
  ): TypedContractMethod<
    [
      _collateralReservationId: BigNumberish,
      _proof: IPayment.ProofStruct,
      _xrplAddress: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeInstruction"
  ): TypedContractMethod<
    [_proof: IPayment.ProofStruct, _xrplAddress: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executeTimelockedCall"
  ): TypedContractMethod<[_encodedCall: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "facetAddress"
  ): TypedContractMethod<[_functionSelector: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "facetAddresses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "facetFunctionSelectors"
  ): TypedContractMethod<[_facet: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "facets"
  ): TypedContractMethod<[], [IDiamondLoupe.FacetStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getAgentVaults"
  ): TypedContractMethod<
    [],
    [
      [bigint[], string[]] & {
        _agentVaultIds: bigint[];
        _agentVaultAddresses: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBalances(string)"
  ): TypedContractMethod<
    [_xrplOwner: string],
    [IReaderFacet.AccountBalancesStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBalances(address)"
  ): TypedContractMethod<
    [_account: AddressLike],
    [IReaderFacet.AccountBalancesStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDefaultInstructionFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getExecuteTimelockedCallTimestamp"
  ): TypedContractMethod<[_encodedCall: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getExecutor"
  ): TypedContractMethod<[_personalAccount: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getExecutorInfo"
  ): TypedContractMethod<
    [],
    [[string, bigint] & { _executor: string; _executorFee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInstructionFee"
  ): TypedContractMethod<[_instructionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNonce"
  ): TypedContractMethod<[_personalAccount: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPausers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPaymentProofValidityDurationSeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPersonalAccount"
  ): TypedContractMethod<[_xrplOwner: string], [string], "view">;
  getFunction(
    nameOrSignature: "getSourceId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTimelockDurationSeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTransactionIdForCollateralReservation"
  ): TypedContractMethod<
    [_collateralReservationId: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUnpausers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVaults"
  ): TypedContractMethod<
    [],
    [
      [bigint[], string[], bigint[]] & {
        _vaultIds: bigint[];
        _vaultAddresses: string[];
        _vaultTypes: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getXrplProviderWallets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "implementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPauser"
  ): TypedContractMethod<[_account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSmartAccount"
  ): TypedContractMethod<
    [_address: AddressLike],
    [[boolean, string] & { _isSmartAccount: boolean; _xrplOwner: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTransactionIdUsed"
  ): TypedContractMethod<[_transactionId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isUnpauser"
  ): TypedContractMethod<[_account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintedFAssets"
  ): TypedContractMethod<
    [
      _transactionId: BytesLike,
      _sourceAddress: string,
      _amount: BigNumberish,
      _underlyingTimestamp: BigNumberish,
      _memoData: BytesLike,
      _executor: AddressLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reserveCollateral"
  ): TypedContractMethod<
    [
      _xrplAddress: string,
      _paymentReference: BytesLike,
      _transactionId: BytesLike
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vaults"
  ): TypedContractMethod<[], [IReaderFacet.VaultDetailsStructOutput[]], "view">;

  getEvent(
    key: "AgentVaultAdded"
  ): TypedContractEvent<
    AgentVaultAddedEvent.InputTuple,
    AgentVaultAddedEvent.OutputTuple,
    AgentVaultAddedEvent.OutputObject
  >;
  getEvent(
    key: "AgentVaultRemoved"
  ): TypedContractEvent<
    AgentVaultRemovedEvent.InputTuple,
    AgentVaultRemovedEvent.OutputTuple,
    AgentVaultRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Approved"
  ): TypedContractEvent<
    ApprovedEvent.InputTuple,
    ApprovedEvent.OutputTuple,
    ApprovedEvent.OutputObject
  >;
  getEvent(
    key: "CallTimelocked"
  ): TypedContractEvent<
    CallTimelockedEvent.InputTuple,
    CallTimelockedEvent.OutputTuple,
    CallTimelockedEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "CollateralReserved"
  ): TypedContractEvent<
    CollateralReservedEvent.InputTuple,
    CollateralReservedEvent.OutputTuple,
    CollateralReservedEvent.OutputObject
  >;
  getEvent(
    key: "DefaultInstructionFeeSet"
  ): TypedContractEvent<
    DefaultInstructionFeeSetEvent.InputTuple,
    DefaultInstructionFeeSetEvent.OutputTuple,
    DefaultInstructionFeeSetEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "DiamondCut"
  ): TypedContractEvent<
    DiamondCutEvent.InputTuple,
    DiamondCutEvent.OutputTuple,
    DiamondCutEvent.OutputObject
  >;
  getEvent(
    key: "DirectMintingExecuted"
  ): TypedContractEvent<
    DirectMintingExecutedEvent.InputTuple,
    DirectMintingExecutedEvent.OutputTuple,
    DirectMintingExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorFeeSet"
  ): TypedContractEvent<
    ExecutorFeeSetEvent.InputTuple,
    ExecutorFeeSetEvent.OutputTuple,
    ExecutorFeeSetEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorRemoved"
  ): TypedContractEvent<
    ExecutorRemovedEvent.InputTuple,
    ExecutorRemovedEvent.OutputTuple,
    ExecutorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorSet(address)"
  ): TypedContractEvent<
    ExecutorSet_address_Event.InputTuple,
    ExecutorSet_address_Event.OutputTuple,
    ExecutorSet_address_Event.OutputObject
  >;
  getEvent(
    key: "ExecutorSet(address,address)"
  ): TypedContractEvent<
    ExecutorSet_address_address_Event.InputTuple,
    ExecutorSet_address_address_Event.OutputTuple,
    ExecutorSet_address_address_Event.OutputObject
  >;
  getEvent(
    key: "FXrpRedeemed"
  ): TypedContractEvent<
    FXrpRedeemedEvent.InputTuple,
    FXrpRedeemedEvent.OutputTuple,
    FXrpRedeemedEvent.OutputObject
  >;
  getEvent(
    key: "FXrpTransferred"
  ): TypedContractEvent<
    FXrpTransferredEvent.InputTuple,
    FXrpTransferredEvent.OutputTuple,
    FXrpTransferredEvent.OutputObject
  >;
  getEvent(
    key: "IgnoreMemoSet"
  ): TypedContractEvent<
    IgnoreMemoSetEvent.InputTuple,
    IgnoreMemoSetEvent.OutputTuple,
    IgnoreMemoSetEvent.OutputObject
  >;
  getEvent(
    key: "InstructionExecuted"
  ): TypedContractEvent<
    InstructionExecutedEvent.InputTuple,
    InstructionExecutedEvent.OutputTuple,
    InstructionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "InstructionFeeRemoved"
  ): TypedContractEvent<
    InstructionFeeRemovedEvent.InputTuple,
    InstructionFeeRemovedEvent.OutputTuple,
    InstructionFeeRemovedEvent.OutputObject
  >;
  getEvent(
    key: "InstructionFeeSet"
  ): TypedContractEvent<
    InstructionFeeSetEvent.InputTuple,
    InstructionFeeSetEvent.OutputTuple,
    InstructionFeeSetEvent.OutputObject
  >;
  getEvent(
    key: "NonceIncreased"
  ): TypedContractEvent<
    NonceIncreasedEvent.InputTuple,
    NonceIncreasedEvent.OutputTuple,
    NonceIncreasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PauserAdded"
  ): TypedContractEvent<
    PauserAddedEvent.InputTuple,
    PauserAddedEvent.OutputTuple,
    PauserAddedEvent.OutputObject
  >;
  getEvent(
    key: "PauserRemoved"
  ): TypedContractEvent<
    PauserRemovedEvent.InputTuple,
    PauserRemovedEvent.OutputTuple,
    PauserRemovedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentProofValidityDurationSecondsSet"
  ): TypedContractEvent<
    PaymentProofValidityDurationSecondsSetEvent.InputTuple,
    PaymentProofValidityDurationSecondsSetEvent.OutputTuple,
    PaymentProofValidityDurationSecondsSetEvent.OutputObject
  >;
  getEvent(
    key: "PersonalAccountCreated"
  ): TypedContractEvent<
    PersonalAccountCreatedEvent.InputTuple,
    PersonalAccountCreatedEvent.OutputTuple,
    PersonalAccountCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PersonalAccountImplementationSet"
  ): TypedContractEvent<
    PersonalAccountImplementationSetEvent.InputTuple,
    PersonalAccountImplementationSetEvent.OutputTuple,
    PersonalAccountImplementationSetEvent.OutputObject
  >;
  getEvent(
    key: "RedeemRequested"
  ): TypedContractEvent<
    RedeemRequestedEvent.InputTuple,
    RedeemRequestedEvent.OutputTuple,
    RedeemRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Redeemed"
  ): TypedContractEvent<
    RedeemedEvent.InputTuple,
    RedeemedEvent.OutputTuple,
    RedeemedEvent.OutputObject
  >;
  getEvent(
    key: "ReplacementFeeSet"
  ): TypedContractEvent<
    ReplacementFeeSetEvent.InputTuple,
    ReplacementFeeSetEvent.OutputTuple,
    ReplacementFeeSetEvent.OutputObject
  >;
  getEvent(
    key: "TimelockDurationSet"
  ): TypedContractEvent<
    TimelockDurationSetEvent.InputTuple,
    TimelockDurationSetEvent.OutputTuple,
    TimelockDurationSetEvent.OutputObject
  >;
  getEvent(
    key: "TimelockedCallCanceled"
  ): TypedContractEvent<
    TimelockedCallCanceledEvent.InputTuple,
    TimelockedCallCanceledEvent.OutputTuple,
    TimelockedCallCanceledEvent.OutputObject
  >;
  getEvent(
    key: "TimelockedCallExecuted"
  ): TypedContractEvent<
    TimelockedCallExecutedEvent.InputTuple,
    TimelockedCallExecutedEvent.OutputTuple,
    TimelockedCallExecutedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UnpauserAdded"
  ): TypedContractEvent<
    UnpauserAddedEvent.InputTuple,
    UnpauserAddedEvent.OutputTuple,
    UnpauserAddedEvent.OutputObject
  >;
  getEvent(
    key: "UnpauserRemoved"
  ): TypedContractEvent<
    UnpauserRemovedEvent.InputTuple,
    UnpauserRemovedEvent.OutputTuple,
    UnpauserRemovedEvent.OutputObject
  >;
  getEvent(
    key: "UserOperationExecuted"
  ): TypedContractEvent<
    UserOperationExecutedEvent.InputTuple,
    UserOperationExecutedEvent.OutputTuple,
    UserOperationExecutedEvent.OutputObject
  >;
  getEvent(
    key: "VaultAdded"
  ): TypedContractEvent<
    VaultAddedEvent.InputTuple,
    VaultAddedEvent.OutputTuple,
    VaultAddedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalClaimed"
  ): TypedContractEvent<
    WithdrawalClaimedEvent.InputTuple,
    WithdrawalClaimedEvent.OutputTuple,
    WithdrawalClaimedEvent.OutputObject
  >;
  getEvent(
    key: "XrplProviderWalletAdded"
  ): TypedContractEvent<
    XrplProviderWalletAddedEvent.InputTuple,
    XrplProviderWalletAddedEvent.OutputTuple,
    XrplProviderWalletAddedEvent.OutputObject
  >;
  getEvent(
    key: "XrplProviderWalletRemoved"
  ): TypedContractEvent<
    XrplProviderWalletRemovedEvent.InputTuple,
    XrplProviderWalletRemovedEvent.OutputTuple,
    XrplProviderWalletRemovedEvent.OutputObject
  >;

  filters: {
    "AgentVaultAdded(uint256,address)": TypedContractEvent<
      AgentVaultAddedEvent.InputTuple,
      AgentVaultAddedEvent.OutputTuple,
      AgentVaultAddedEvent.OutputObject
    >;
    AgentVaultAdded: TypedContractEvent<
      AgentVaultAddedEvent.InputTuple,
      AgentVaultAddedEvent.OutputTuple,
      AgentVaultAddedEvent.OutputObject
    >;

    "AgentVaultRemoved(uint256,address)": TypedContractEvent<
      AgentVaultRemovedEvent.InputTuple,
      AgentVaultRemovedEvent.OutputTuple,
      AgentVaultRemovedEvent.OutputObject
    >;
    AgentVaultRemoved: TypedContractEvent<
      AgentVaultRemovedEvent.InputTuple,
      AgentVaultRemovedEvent.OutputTuple,
      AgentVaultRemovedEvent.OutputObject
    >;

    "Approved(address,address,address,uint256)": TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;
    Approved: TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;

    "CallTimelocked(bytes,bytes32,uint256)": TypedContractEvent<
      CallTimelockedEvent.InputTuple,
      CallTimelockedEvent.OutputTuple,
      CallTimelockedEvent.OutputObject
    >;
    CallTimelocked: TypedContractEvent<
      CallTimelockedEvent.InputTuple,
      CallTimelockedEvent.OutputTuple,
      CallTimelockedEvent.OutputObject
    >;

    "Claimed(address,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "CollateralReserved(address,bytes32,bytes32,string,uint256,address,uint256,address,uint256)": TypedContractEvent<
      CollateralReservedEvent.InputTuple,
      CollateralReservedEvent.OutputTuple,
      CollateralReservedEvent.OutputObject
    >;
    CollateralReserved: TypedContractEvent<
      CollateralReservedEvent.InputTuple,
      CollateralReservedEvent.OutputTuple,
      CollateralReservedEvent.OutputObject
    >;

    "DefaultInstructionFeeSet(uint256)": TypedContractEvent<
      DefaultInstructionFeeSetEvent.InputTuple,
      DefaultInstructionFeeSetEvent.OutputTuple,
      DefaultInstructionFeeSetEvent.OutputObject
    >;
    DefaultInstructionFeeSet: TypedContractEvent<
      DefaultInstructionFeeSetEvent.InputTuple,
      DefaultInstructionFeeSetEvent.OutputTuple,
      DefaultInstructionFeeSetEvent.OutputObject
    >;

    "Deposited(address,address,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "DiamondCut(tuple[],address,bytes)": TypedContractEvent<
      DiamondCutEvent.InputTuple,
      DiamondCutEvent.OutputTuple,
      DiamondCutEvent.OutputObject
    >;
    DiamondCut: TypedContractEvent<
      DiamondCutEvent.InputTuple,
      DiamondCutEvent.OutputTuple,
      DiamondCutEvent.OutputObject
    >;

    "DirectMintingExecuted(address,bytes32,string,uint256,uint256,address)": TypedContractEvent<
      DirectMintingExecutedEvent.InputTuple,
      DirectMintingExecutedEvent.OutputTuple,
      DirectMintingExecutedEvent.OutputObject
    >;
    DirectMintingExecuted: TypedContractEvent<
      DirectMintingExecutedEvent.InputTuple,
      DirectMintingExecutedEvent.OutputTuple,
      DirectMintingExecutedEvent.OutputObject
    >;

    "ExecutorFeeSet(uint256)": TypedContractEvent<
      ExecutorFeeSetEvent.InputTuple,
      ExecutorFeeSetEvent.OutputTuple,
      ExecutorFeeSetEvent.OutputObject
    >;
    ExecutorFeeSet: TypedContractEvent<
      ExecutorFeeSetEvent.InputTuple,
      ExecutorFeeSetEvent.OutputTuple,
      ExecutorFeeSetEvent.OutputObject
    >;

    "ExecutorRemoved(address)": TypedContractEvent<
      ExecutorRemovedEvent.InputTuple,
      ExecutorRemovedEvent.OutputTuple,
      ExecutorRemovedEvent.OutputObject
    >;
    ExecutorRemoved: TypedContractEvent<
      ExecutorRemovedEvent.InputTuple,
      ExecutorRemovedEvent.OutputTuple,
      ExecutorRemovedEvent.OutputObject
    >;

    "ExecutorSet(address)": TypedContractEvent<
      ExecutorSet_address_Event.InputTuple,
      ExecutorSet_address_Event.OutputTuple,
      ExecutorSet_address_Event.OutputObject
    >;
    "ExecutorSet(address,address)": TypedContractEvent<
      ExecutorSet_address_address_Event.InputTuple,
      ExecutorSet_address_address_Event.OutputTuple,
      ExecutorSet_address_address_Event.OutputObject
    >;

    "FXrpRedeemed(address,uint256,uint256,address,uint256)": TypedContractEvent<
      FXrpRedeemedEvent.InputTuple,
      FXrpRedeemedEvent.OutputTuple,
      FXrpRedeemedEvent.OutputObject
    >;
    FXrpRedeemed: TypedContractEvent<
      FXrpRedeemedEvent.InputTuple,
      FXrpRedeemedEvent.OutputTuple,
      FXrpRedeemedEvent.OutputObject
    >;

    "FXrpTransferred(address,address,uint256)": TypedContractEvent<
      FXrpTransferredEvent.InputTuple,
      FXrpTransferredEvent.OutputTuple,
      FXrpTransferredEvent.OutputObject
    >;
    FXrpTransferred: TypedContractEvent<
      FXrpTransferredEvent.InputTuple,
      FXrpTransferredEvent.OutputTuple,
      FXrpTransferredEvent.OutputObject
    >;

    "IgnoreMemoSet(address,bytes32)": TypedContractEvent<
      IgnoreMemoSetEvent.InputTuple,
      IgnoreMemoSetEvent.OutputTuple,
      IgnoreMemoSetEvent.OutputObject
    >;
    IgnoreMemoSet: TypedContractEvent<
      IgnoreMemoSetEvent.InputTuple,
      IgnoreMemoSetEvent.OutputTuple,
      IgnoreMemoSetEvent.OutputObject
    >;

    "InstructionExecuted(address,bytes32,bytes32,string,uint256)": TypedContractEvent<
      InstructionExecutedEvent.InputTuple,
      InstructionExecutedEvent.OutputTuple,
      InstructionExecutedEvent.OutputObject
    >;
    InstructionExecuted: TypedContractEvent<
      InstructionExecutedEvent.InputTuple,
      InstructionExecutedEvent.OutputTuple,
      InstructionExecutedEvent.OutputObject
    >;

    "InstructionFeeRemoved(uint256)": TypedContractEvent<
      InstructionFeeRemovedEvent.InputTuple,
      InstructionFeeRemovedEvent.OutputTuple,
      InstructionFeeRemovedEvent.OutputObject
    >;
    InstructionFeeRemoved: TypedContractEvent<
      InstructionFeeRemovedEvent.InputTuple,
      InstructionFeeRemovedEvent.OutputTuple,
      InstructionFeeRemovedEvent.OutputObject
    >;

    "InstructionFeeSet(uint256,uint256)": TypedContractEvent<
      InstructionFeeSetEvent.InputTuple,
      InstructionFeeSetEvent.OutputTuple,
      InstructionFeeSetEvent.OutputObject
    >;
    InstructionFeeSet: TypedContractEvent<
      InstructionFeeSetEvent.InputTuple,
      InstructionFeeSetEvent.OutputTuple,
      InstructionFeeSetEvent.OutputObject
    >;

    "NonceIncreased(address,uint256)": TypedContractEvent<
      NonceIncreasedEvent.InputTuple,
      NonceIncreasedEvent.OutputTuple,
      NonceIncreasedEvent.OutputObject
    >;
    NonceIncreased: TypedContractEvent<
      NonceIncreasedEvent.InputTuple,
      NonceIncreasedEvent.OutputTuple,
      NonceIncreasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PauserAdded(address)": TypedContractEvent<
      PauserAddedEvent.InputTuple,
      PauserAddedEvent.OutputTuple,
      PauserAddedEvent.OutputObject
    >;
    PauserAdded: TypedContractEvent<
      PauserAddedEvent.InputTuple,
      PauserAddedEvent.OutputTuple,
      PauserAddedEvent.OutputObject
    >;

    "PauserRemoved(address)": TypedContractEvent<
      PauserRemovedEvent.InputTuple,
      PauserRemovedEvent.OutputTuple,
      PauserRemovedEvent.OutputObject
    >;
    PauserRemoved: TypedContractEvent<
      PauserRemovedEvent.InputTuple,
      PauserRemovedEvent.OutputTuple,
      PauserRemovedEvent.OutputObject
    >;

    "PaymentProofValidityDurationSecondsSet(uint256)": TypedContractEvent<
      PaymentProofValidityDurationSecondsSetEvent.InputTuple,
      PaymentProofValidityDurationSecondsSetEvent.OutputTuple,
      PaymentProofValidityDurationSecondsSetEvent.OutputObject
    >;
    PaymentProofValidityDurationSecondsSet: TypedContractEvent<
      PaymentProofValidityDurationSecondsSetEvent.InputTuple,
      PaymentProofValidityDurationSecondsSetEvent.OutputTuple,
      PaymentProofValidityDurationSecondsSetEvent.OutputObject
    >;

    "PersonalAccountCreated(address,string)": TypedContractEvent<
      PersonalAccountCreatedEvent.InputTuple,
      PersonalAccountCreatedEvent.OutputTuple,
      PersonalAccountCreatedEvent.OutputObject
    >;
    PersonalAccountCreated: TypedContractEvent<
      PersonalAccountCreatedEvent.InputTuple,
      PersonalAccountCreatedEvent.OutputTuple,
      PersonalAccountCreatedEvent.OutputObject
    >;

    "PersonalAccountImplementationSet(address)": TypedContractEvent<
      PersonalAccountImplementationSetEvent.InputTuple,
      PersonalAccountImplementationSetEvent.OutputTuple,
      PersonalAccountImplementationSetEvent.OutputObject
    >;
    PersonalAccountImplementationSet: TypedContractEvent<
      PersonalAccountImplementationSetEvent.InputTuple,
      PersonalAccountImplementationSetEvent.OutputTuple,
      PersonalAccountImplementationSetEvent.OutputObject
    >;

    "RedeemRequested(address,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RedeemRequestedEvent.InputTuple,
      RedeemRequestedEvent.OutputTuple,
      RedeemRequestedEvent.OutputObject
    >;
    RedeemRequested: TypedContractEvent<
      RedeemRequestedEvent.InputTuple,
      RedeemRequestedEvent.OutputTuple,
      RedeemRequestedEvent.OutputObject
    >;

    "Redeemed(address,address,uint256,uint256)": TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;
    Redeemed: TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;

    "ReplacementFeeSet(address,bytes32,uint64)": TypedContractEvent<
      ReplacementFeeSetEvent.InputTuple,
      ReplacementFeeSetEvent.OutputTuple,
      ReplacementFeeSetEvent.OutputObject
    >;
    ReplacementFeeSet: TypedContractEvent<
      ReplacementFeeSetEvent.InputTuple,
      ReplacementFeeSetEvent.OutputTuple,
      ReplacementFeeSetEvent.OutputObject
    >;

    "TimelockDurationSet(uint256)": TypedContractEvent<
      TimelockDurationSetEvent.InputTuple,
      TimelockDurationSetEvent.OutputTuple,
      TimelockDurationSetEvent.OutputObject
    >;
    TimelockDurationSet: TypedContractEvent<
      TimelockDurationSetEvent.InputTuple,
      TimelockDurationSetEvent.OutputTuple,
      TimelockDurationSetEvent.OutputObject
    >;

    "TimelockedCallCanceled(bytes32)": TypedContractEvent<
      TimelockedCallCanceledEvent.InputTuple,
      TimelockedCallCanceledEvent.OutputTuple,
      TimelockedCallCanceledEvent.OutputObject
    >;
    TimelockedCallCanceled: TypedContractEvent<
      TimelockedCallCanceledEvent.InputTuple,
      TimelockedCallCanceledEvent.OutputTuple,
      TimelockedCallCanceledEvent.OutputObject
    >;

    "TimelockedCallExecuted(bytes32)": TypedContractEvent<
      TimelockedCallExecutedEvent.InputTuple,
      TimelockedCallExecutedEvent.OutputTuple,
      TimelockedCallExecutedEvent.OutputObject
    >;
    TimelockedCallExecuted: TypedContractEvent<
      TimelockedCallExecutedEvent.InputTuple,
      TimelockedCallExecutedEvent.OutputTuple,
      TimelockedCallExecutedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UnpauserAdded(address)": TypedContractEvent<
      UnpauserAddedEvent.InputTuple,
      UnpauserAddedEvent.OutputTuple,
      UnpauserAddedEvent.OutputObject
    >;
    UnpauserAdded: TypedContractEvent<
      UnpauserAddedEvent.InputTuple,
      UnpauserAddedEvent.OutputTuple,
      UnpauserAddedEvent.OutputObject
    >;

    "UnpauserRemoved(address)": TypedContractEvent<
      UnpauserRemovedEvent.InputTuple,
      UnpauserRemovedEvent.OutputTuple,
      UnpauserRemovedEvent.OutputObject
    >;
    UnpauserRemoved: TypedContractEvent<
      UnpauserRemovedEvent.InputTuple,
      UnpauserRemovedEvent.OutputTuple,
      UnpauserRemovedEvent.OutputObject
    >;

    "UserOperationExecuted(address,uint256)": TypedContractEvent<
      UserOperationExecutedEvent.InputTuple,
      UserOperationExecutedEvent.OutputTuple,
      UserOperationExecutedEvent.OutputObject
    >;
    UserOperationExecuted: TypedContractEvent<
      UserOperationExecutedEvent.InputTuple,
      UserOperationExecutedEvent.OutputTuple,
      UserOperationExecutedEvent.OutputObject
    >;

    "VaultAdded(uint256,address,uint8)": TypedContractEvent<
      VaultAddedEvent.InputTuple,
      VaultAddedEvent.OutputTuple,
      VaultAddedEvent.OutputObject
    >;
    VaultAdded: TypedContractEvent<
      VaultAddedEvent.InputTuple,
      VaultAddedEvent.OutputTuple,
      VaultAddedEvent.OutputObject
    >;

    "WithdrawalClaimed(address,address,uint256,uint256)": TypedContractEvent<
      WithdrawalClaimedEvent.InputTuple,
      WithdrawalClaimedEvent.OutputTuple,
      WithdrawalClaimedEvent.OutputObject
    >;
    WithdrawalClaimed: TypedContractEvent<
      WithdrawalClaimedEvent.InputTuple,
      WithdrawalClaimedEvent.OutputTuple,
      WithdrawalClaimedEvent.OutputObject
    >;

    "XrplProviderWalletAdded(string)": TypedContractEvent<
      XrplProviderWalletAddedEvent.InputTuple,
      XrplProviderWalletAddedEvent.OutputTuple,
      XrplProviderWalletAddedEvent.OutputObject
    >;
    XrplProviderWalletAdded: TypedContractEvent<
      XrplProviderWalletAddedEvent.InputTuple,
      XrplProviderWalletAddedEvent.OutputTuple,
      XrplProviderWalletAddedEvent.OutputObject
    >;

    "XrplProviderWalletRemoved(string)": TypedContractEvent<
      XrplProviderWalletRemovedEvent.InputTuple,
      XrplProviderWalletRemovedEvent.OutputTuple,
      XrplProviderWalletRemovedEvent.OutputObject
    >;
    XrplProviderWalletRemoved: TypedContractEvent<
      XrplProviderWalletRemovedEvent.InputTuple,
      XrplProviderWalletRemovedEvent.OutputTuple,
      XrplProviderWalletRemovedEvent.OutputObject
    >;
  };
}
