/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IPaymentProofsFacetInterface extends Interface {
  getFunction(
    nameOrSignature: "getPaymentProofValidityDurationSeconds" | "getSourceId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PaymentProofValidityDurationSecondsSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getPaymentProofValidityDurationSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSourceId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getPaymentProofValidityDurationSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSourceId",
    data: BytesLike
  ): Result;
}

export namespace PaymentProofValidityDurationSecondsSetEvent {
  export type InputTuple = [paymentProofValidityDurationSeconds: BigNumberish];
  export type OutputTuple = [paymentProofValidityDurationSeconds: bigint];
  export interface OutputObject {
    paymentProofValidityDurationSeconds: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPaymentProofsFacet extends BaseContract {
  connect(runner?: ContractRunner | null): IPaymentProofsFacet;
  waitForDeployment(): Promise<this>;

  interface: IPaymentProofsFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPaymentProofValidityDurationSeconds: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  getSourceId: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPaymentProofValidityDurationSeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSourceId"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "PaymentProofValidityDurationSecondsSet"
  ): TypedContractEvent<
    PaymentProofValidityDurationSecondsSetEvent.InputTuple,
    PaymentProofValidityDurationSecondsSetEvent.OutputTuple,
    PaymentProofValidityDurationSecondsSetEvent.OutputObject
  >;

  filters: {
    "PaymentProofValidityDurationSecondsSet(uint256)": TypedContractEvent<
      PaymentProofValidityDurationSecondsSetEvent.InputTuple,
      PaymentProofValidityDurationSecondsSetEvent.OutputTuple,
      PaymentProofValidityDurationSecondsSetEvent.OutputObject
    >;
    PaymentProofValidityDurationSecondsSet: TypedContractEvent<
      PaymentProofValidityDurationSecondsSetEvent.InputTuple,
      PaymentProofValidityDurationSecondsSetEvent.OutputTuple,
      PaymentProofValidityDurationSecondsSetEvent.OutputObject
    >;
  };
}
