/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IReaderFacet {
  export type AgentVaultDetailsStruct = {
    agentVaultId: BigNumberish;
    agentVaultAddress: AddressLike;
  };

  export type AgentVaultDetailsStructOutput = [
    agentVaultId: bigint,
    agentVaultAddress: string
  ] & { agentVaultId: bigint; agentVaultAddress: string };

  export type TokenBalanceStruct = {
    token: AddressLike;
    balance: BigNumberish;
  };

  export type TokenBalanceStructOutput = [token: string, balance: bigint] & {
    token: string;
    balance: bigint;
  };

  export type VaultBalanceStruct = {
    vaultId: BigNumberish;
    vaultAddress: AddressLike;
    vaultType: BigNumberish;
    shares: BigNumberish;
    assets: BigNumberish;
  };

  export type VaultBalanceStructOutput = [
    vaultId: bigint,
    vaultAddress: string,
    vaultType: bigint,
    shares: bigint,
    assets: bigint
  ] & {
    vaultId: bigint;
    vaultAddress: string;
    vaultType: bigint;
    shares: bigint;
    assets: bigint;
  };

  export type AccountBalancesStruct = {
    natBalance: BigNumberish;
    wNat: IReaderFacet.TokenBalanceStruct;
    fXrp: IReaderFacet.TokenBalanceStruct;
    vaults: IReaderFacet.VaultBalanceStruct[];
  };

  export type AccountBalancesStructOutput = [
    natBalance: bigint,
    wNat: IReaderFacet.TokenBalanceStructOutput,
    fXrp: IReaderFacet.TokenBalanceStructOutput,
    vaults: IReaderFacet.VaultBalanceStructOutput[]
  ] & {
    natBalance: bigint;
    wNat: IReaderFacet.TokenBalanceStructOutput;
    fXrp: IReaderFacet.TokenBalanceStructOutput;
    vaults: IReaderFacet.VaultBalanceStructOutput[];
  };

  export type VaultDetailsStruct = {
    vaultId: BigNumberish;
    vaultAddress: AddressLike;
    vaultType: BigNumberish;
  };

  export type VaultDetailsStructOutput = [
    vaultId: bigint,
    vaultAddress: string,
    vaultType: bigint
  ] & { vaultId: bigint; vaultAddress: string; vaultType: bigint };
}

export interface IReaderFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentVaults"
      | "getBalances(string)"
      | "getBalances(address)"
      | "isSmartAccount"
      | "vaults"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "agentVaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalances(string)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalances(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSmartAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vaults", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "agentVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalances(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalances(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSmartAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;
}

export interface IReaderFacet extends BaseContract {
  connect(runner?: ContractRunner | null): IReaderFacet;
  waitForDeployment(): Promise<this>;

  interface: IReaderFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentVaults: TypedContractMethod<
    [],
    [IReaderFacet.AgentVaultDetailsStructOutput[]],
    "view"
  >;

  "getBalances(string)": TypedContractMethod<
    [_xrplOwner: string],
    [IReaderFacet.AccountBalancesStructOutput],
    "view"
  >;

  "getBalances(address)": TypedContractMethod<
    [_account: AddressLike],
    [IReaderFacet.AccountBalancesStructOutput],
    "view"
  >;

  isSmartAccount: TypedContractMethod<
    [_address: AddressLike],
    [[boolean, string] & { _isSmartAccount: boolean; _xrplOwner: string }],
    "view"
  >;

  vaults: TypedContractMethod<
    [],
    [IReaderFacet.VaultDetailsStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentVaults"
  ): TypedContractMethod<
    [],
    [IReaderFacet.AgentVaultDetailsStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBalances(string)"
  ): TypedContractMethod<
    [_xrplOwner: string],
    [IReaderFacet.AccountBalancesStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBalances(address)"
  ): TypedContractMethod<
    [_account: AddressLike],
    [IReaderFacet.AccountBalancesStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSmartAccount"
  ): TypedContractMethod<
    [_address: AddressLike],
    [[boolean, string] & { _isSmartAccount: boolean; _xrplOwner: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "vaults"
  ): TypedContractMethod<[], [IReaderFacet.VaultDetailsStructOutput[]], "view">;

  filters: {};
}
