/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IRedeemExtendedSettingsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "minimumRedeemAmountUBA"
      | "setMinimumRedeemAmountUBA"
      | "setSystemRedemptionFeeBIPS"
      | "setSystemRedemptionFeeReceiver"
      | "systemRedemptionFeeBIPS"
      | "systemRedemptionFeeReceiver"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "minimumRedeemAmountUBA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMinimumRedeemAmountUBA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSystemRedemptionFeeBIPS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSystemRedemptionFeeReceiver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "systemRedemptionFeeBIPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "systemRedemptionFeeReceiver",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "minimumRedeemAmountUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinimumRedeemAmountUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSystemRedemptionFeeBIPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSystemRedemptionFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "systemRedemptionFeeBIPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "systemRedemptionFeeReceiver",
    data: BytesLike
  ): Result;
}

export interface IRedeemExtendedSettings extends BaseContract {
  connect(runner?: ContractRunner | null): IRedeemExtendedSettings;
  waitForDeployment(): Promise<this>;

  interface: IRedeemExtendedSettingsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  minimumRedeemAmountUBA: TypedContractMethod<[], [bigint], "view">;

  setMinimumRedeemAmountUBA: TypedContractMethod<
    [_valueUBA: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSystemRedemptionFeeBIPS: TypedContractMethod<
    [_feeBIPS: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSystemRedemptionFeeReceiver: TypedContractMethod<
    [_receiver: AddressLike],
    [void],
    "nonpayable"
  >;

  systemRedemptionFeeBIPS: TypedContractMethod<[], [bigint], "view">;

  systemRedemptionFeeReceiver: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "minimumRedeemAmountUBA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setMinimumRedeemAmountUBA"
  ): TypedContractMethod<[_valueUBA: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSystemRedemptionFeeBIPS"
  ): TypedContractMethod<[_feeBIPS: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSystemRedemptionFeeReceiver"
  ): TypedContractMethod<[_receiver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "systemRedemptionFeeBIPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "systemRedemptionFeeReceiver"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
