/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IXRPPayment {
  export type RequestBodyStruct = {
    transactionId: BytesLike;
    proofOwner: AddressLike;
  };

  export type RequestBodyStructOutput = [
    transactionId: string,
    proofOwner: string
  ] & { transactionId: string; proofOwner: string };

  export type ResponseBodyStruct = {
    blockNumber: BigNumberish;
    blockTimestamp: BigNumberish;
    sourceAddress: string;
    sourceAddressHash: BytesLike;
    receivingAddressHash: BytesLike;
    intendedReceivingAddressHash: BytesLike;
    spentAmount: BigNumberish;
    intendedSpentAmount: BigNumberish;
    receivedAmount: BigNumberish;
    intendedReceivedAmount: BigNumberish;
    hasMemoData: boolean;
    firstMemoData: BytesLike;
    hasDestinationTag: boolean;
    destinationTag: BigNumberish;
    status: BigNumberish;
  };

  export type ResponseBodyStructOutput = [
    blockNumber: bigint,
    blockTimestamp: bigint,
    sourceAddress: string,
    sourceAddressHash: string,
    receivingAddressHash: string,
    intendedReceivingAddressHash: string,
    spentAmount: bigint,
    intendedSpentAmount: bigint,
    receivedAmount: bigint,
    intendedReceivedAmount: bigint,
    hasMemoData: boolean,
    firstMemoData: string,
    hasDestinationTag: boolean,
    destinationTag: bigint,
    status: bigint
  ] & {
    blockNumber: bigint;
    blockTimestamp: bigint;
    sourceAddress: string;
    sourceAddressHash: string;
    receivingAddressHash: string;
    intendedReceivingAddressHash: string;
    spentAmount: bigint;
    intendedSpentAmount: bigint;
    receivedAmount: bigint;
    intendedReceivedAmount: bigint;
    hasMemoData: boolean;
    firstMemoData: string;
    hasDestinationTag: boolean;
    destinationTag: bigint;
    status: bigint;
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IXRPPayment.RequestBodyStruct;
    responseBody: IXRPPayment.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IXRPPayment.RequestBodyStructOutput,
    responseBody: IXRPPayment.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IXRPPayment.RequestBodyStructOutput;
    responseBody: IXRPPayment.ResponseBodyStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    data: IXRPPayment.ResponseStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    data: IXRPPayment.ResponseStructOutput
  ] & { merkleProof: string[]; data: IXRPPayment.ResponseStructOutput };
}

export declare namespace RedemptionRequestInfo {
  export type DataExtStruct = {
    redemptionRequestId: BigNumberish;
    status: BigNumberish;
    agentVault: AddressLike;
    redeemer: AddressLike;
    paymentAddress: string;
    paymentReference: BytesLike;
    valueUBA: BigNumberish;
    feeUBA: BigNumberish;
    poolFeeShareBIPS: BigNumberish;
    firstUnderlyingBlock: BigNumberish;
    lastUnderlyingBlock: BigNumberish;
    lastUnderlyingTimestamp: BigNumberish;
    timestamp: BigNumberish;
    poolSelfClose: boolean;
    transferToCoreVault: boolean;
    executor: AddressLike;
    executorFeeNatWei: BigNumberish;
    requiresDestinationTag: boolean;
    destinationTag: BigNumberish;
  };

  export type DataExtStructOutput = [
    redemptionRequestId: bigint,
    status: bigint,
    agentVault: string,
    redeemer: string,
    paymentAddress: string,
    paymentReference: string,
    valueUBA: bigint,
    feeUBA: bigint,
    poolFeeShareBIPS: bigint,
    firstUnderlyingBlock: bigint,
    lastUnderlyingBlock: bigint,
    lastUnderlyingTimestamp: bigint,
    timestamp: bigint,
    poolSelfClose: boolean,
    transferToCoreVault: boolean,
    executor: string,
    executorFeeNatWei: bigint,
    requiresDestinationTag: boolean,
    destinationTag: bigint
  ] & {
    redemptionRequestId: bigint;
    status: bigint;
    agentVault: string;
    redeemer: string;
    paymentAddress: string;
    paymentReference: string;
    valueUBA: bigint;
    feeUBA: bigint;
    poolFeeShareBIPS: bigint;
    firstUnderlyingBlock: bigint;
    lastUnderlyingBlock: bigint;
    lastUnderlyingTimestamp: bigint;
    timestamp: bigint;
    poolSelfClose: boolean;
    transferToCoreVault: boolean;
    executor: string;
    executorFeeNatWei: bigint;
    requiresDestinationTag: boolean;
    destinationTag: bigint;
  };
}

export declare namespace IXRPPaymentNonexistence {
  export type RequestBodyStruct = {
    minimalBlockNumber: BigNumberish;
    deadlineBlockNumber: BigNumberish;
    deadlineTimestamp: BigNumberish;
    destinationAddressHash: BytesLike;
    amount: BigNumberish;
    checkFirstMemoData: boolean;
    firstMemoDataHash: BytesLike;
    checkDestinationTag: boolean;
    destinationTag: BigNumberish;
    proofOwner: AddressLike;
  };

  export type RequestBodyStructOutput = [
    minimalBlockNumber: bigint,
    deadlineBlockNumber: bigint,
    deadlineTimestamp: bigint,
    destinationAddressHash: string,
    amount: bigint,
    checkFirstMemoData: boolean,
    firstMemoDataHash: string,
    checkDestinationTag: boolean,
    destinationTag: bigint,
    proofOwner: string
  ] & {
    minimalBlockNumber: bigint;
    deadlineBlockNumber: bigint;
    deadlineTimestamp: bigint;
    destinationAddressHash: string;
    amount: bigint;
    checkFirstMemoData: boolean;
    firstMemoDataHash: string;
    checkDestinationTag: boolean;
    destinationTag: bigint;
    proofOwner: string;
  };

  export type ResponseBodyStruct = {
    minimalBlockTimestamp: BigNumberish;
    firstOverflowBlockNumber: BigNumberish;
    firstOverflowBlockTimestamp: BigNumberish;
  };

  export type ResponseBodyStructOutput = [
    minimalBlockTimestamp: bigint,
    firstOverflowBlockNumber: bigint,
    firstOverflowBlockTimestamp: bigint
  ] & {
    minimalBlockTimestamp: bigint;
    firstOverflowBlockNumber: bigint;
    firstOverflowBlockTimestamp: bigint;
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IXRPPaymentNonexistence.RequestBodyStruct;
    responseBody: IXRPPaymentNonexistence.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IXRPPaymentNonexistence.RequestBodyStructOutput,
    responseBody: IXRPPaymentNonexistence.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IXRPPaymentNonexistence.RequestBodyStructOutput;
    responseBody: IXRPPaymentNonexistence.ResponseBodyStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    data: IXRPPaymentNonexistence.ResponseStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    data: IXRPPaymentNonexistence.ResponseStructOutput
  ] & {
    merkleProof: string[];
    data: IXRPPaymentNonexistence.ResponseStructOutput;
  };
}

export interface IRedeemExtendedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confirmXRPRedemptionPayment"
      | "redeemAmount"
      | "redeemWithTag"
      | "redeemWithTagSupported"
      | "redemptionRequestInfoExt"
      | "xrpRedemptionPaymentDefault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RedemptionAmountIncomplete"
      | "RedemptionWithTagRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confirmXRPRedemptionPayment",
    values: [IXRPPayment.ProofStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemAmount",
    values: [BigNumberish, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemWithTag",
    values: [BigNumberish, string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemWithTagSupported",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redemptionRequestInfoExt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "xrpRedemptionPaymentDefault",
    values: [IXRPPaymentNonexistence.ProofStruct, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "confirmXRPRedemptionPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemWithTag",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemWithTagSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redemptionRequestInfoExt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xrpRedemptionPaymentDefault",
    data: BytesLike
  ): Result;
}

export namespace RedemptionAmountIncompleteEvent {
  export type InputTuple = [
    redeemer: AddressLike,
    remainingAmountUBA: BigNumberish
  ];
  export type OutputTuple = [redeemer: string, remainingAmountUBA: bigint];
  export interface OutputObject {
    redeemer: string;
    remainingAmountUBA: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionWithTagRequestedEvent {
  export type InputTuple = [
    agentVault: AddressLike,
    redeemer: AddressLike,
    requestId: BigNumberish,
    paymentAddress: string,
    valueUBA: BigNumberish,
    feeUBA: BigNumberish,
    firstUnderlyingBlock: BigNumberish,
    lastUnderlyingBlock: BigNumberish,
    lastUnderlyingTimestamp: BigNumberish,
    paymentReference: BytesLike,
    executor: AddressLike,
    executorFeeNatWei: BigNumberish,
    destinationTag: BigNumberish
  ];
  export type OutputTuple = [
    agentVault: string,
    redeemer: string,
    requestId: bigint,
    paymentAddress: string,
    valueUBA: bigint,
    feeUBA: bigint,
    firstUnderlyingBlock: bigint,
    lastUnderlyingBlock: bigint,
    lastUnderlyingTimestamp: bigint,
    paymentReference: string,
    executor: string,
    executorFeeNatWei: bigint,
    destinationTag: bigint
  ];
  export interface OutputObject {
    agentVault: string;
    redeemer: string;
    requestId: bigint;
    paymentAddress: string;
    valueUBA: bigint;
    feeUBA: bigint;
    firstUnderlyingBlock: bigint;
    lastUnderlyingBlock: bigint;
    lastUnderlyingTimestamp: bigint;
    paymentReference: string;
    executor: string;
    executorFeeNatWei: bigint;
    destinationTag: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IRedeemExtended extends BaseContract {
  connect(runner?: ContractRunner | null): IRedeemExtended;
  waitForDeployment(): Promise<this>;

  interface: IRedeemExtendedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confirmXRPRedemptionPayment: TypedContractMethod<
    [_payment: IXRPPayment.ProofStruct, _redemptionRequestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  redeemAmount: TypedContractMethod<
    [
      _amountUBA: BigNumberish,
      _redeemerUnderlyingAddressString: string,
      _executor: AddressLike
    ],
    [bigint],
    "payable"
  >;

  redeemWithTag: TypedContractMethod<
    [
      _amountUBA: BigNumberish,
      _redeemerUnderlyingAddressString: string,
      _executor: AddressLike,
      _destinationTag: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  redeemWithTagSupported: TypedContractMethod<[], [boolean], "view">;

  redemptionRequestInfoExt: TypedContractMethod<
    [_redemptionRequestId: BigNumberish],
    [RedemptionRequestInfo.DataExtStructOutput],
    "view"
  >;

  xrpRedemptionPaymentDefault: TypedContractMethod<
    [
      _proof: IXRPPaymentNonexistence.ProofStruct,
      _redemptionRequestId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confirmXRPRedemptionPayment"
  ): TypedContractMethod<
    [_payment: IXRPPayment.ProofStruct, _redemptionRequestId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redeemAmount"
  ): TypedContractMethod<
    [
      _amountUBA: BigNumberish,
      _redeemerUnderlyingAddressString: string,
      _executor: AddressLike
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "redeemWithTag"
  ): TypedContractMethod<
    [
      _amountUBA: BigNumberish,
      _redeemerUnderlyingAddressString: string,
      _executor: AddressLike,
      _destinationTag: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "redeemWithTagSupported"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "redemptionRequestInfoExt"
  ): TypedContractMethod<
    [_redemptionRequestId: BigNumberish],
    [RedemptionRequestInfo.DataExtStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "xrpRedemptionPaymentDefault"
  ): TypedContractMethod<
    [
      _proof: IXRPPaymentNonexistence.ProofStruct,
      _redemptionRequestId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "RedemptionAmountIncomplete"
  ): TypedContractEvent<
    RedemptionAmountIncompleteEvent.InputTuple,
    RedemptionAmountIncompleteEvent.OutputTuple,
    RedemptionAmountIncompleteEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionWithTagRequested"
  ): TypedContractEvent<
    RedemptionWithTagRequestedEvent.InputTuple,
    RedemptionWithTagRequestedEvent.OutputTuple,
    RedemptionWithTagRequestedEvent.OutputObject
  >;

  filters: {
    "RedemptionAmountIncomplete(address,uint256)": TypedContractEvent<
      RedemptionAmountIncompleteEvent.InputTuple,
      RedemptionAmountIncompleteEvent.OutputTuple,
      RedemptionAmountIncompleteEvent.OutputObject
    >;
    RedemptionAmountIncomplete: TypedContractEvent<
      RedemptionAmountIncompleteEvent.InputTuple,
      RedemptionAmountIncompleteEvent.OutputTuple,
      RedemptionAmountIncompleteEvent.OutputObject
    >;

    "RedemptionWithTagRequested(address,address,uint256,string,uint256,uint256,uint256,uint256,uint256,bytes32,address,uint256,uint256)": TypedContractEvent<
      RedemptionWithTagRequestedEvent.InputTuple,
      RedemptionWithTagRequestedEvent.OutputTuple,
      RedemptionWithTagRequestedEvent.OutputObject
    >;
    RedemptionWithTagRequested: TypedContractEvent<
      RedemptionWithTagRequestedEvent.InputTuple,
      RedemptionWithTagRequestedEvent.OutputTuple,
      RedemptionWithTagRequestedEvent.OutputObject
    >;
  };
}
