/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IRedemptionTimeExtensionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "redemptionPaymentExtensionSeconds"
      | "setRedemptionPaymentExtensionSeconds"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "redemptionPaymentExtensionSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRedemptionPaymentExtensionSeconds",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "redemptionPaymentExtensionSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRedemptionPaymentExtensionSeconds",
    data: BytesLike
  ): Result;
}

export interface IRedemptionTimeExtension extends BaseContract {
  connect(runner?: ContractRunner | null): IRedemptionTimeExtension;
  waitForDeployment(): Promise<this>;

  interface: IRedemptionTimeExtensionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  redemptionPaymentExtensionSeconds: TypedContractMethod<[], [bigint], "view">;

  setRedemptionPaymentExtensionSeconds: TypedContractMethod<
    [_value: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "redemptionPaymentExtensionSeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setRedemptionPaymentExtensionSeconds"
  ): TypedContractMethod<[_value: BigNumberish], [void], "nonpayable">;

  filters: {};
}
