/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ITimelockFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "executeTimelockedCall"
      | "getExecuteTimelockedCallTimestamp"
      | "getTimelockDurationSeconds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CallTimelocked"
      | "TimelockDurationSet"
      | "TimelockedCallCanceled"
      | "TimelockedCallExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "executeTimelockedCall",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExecuteTimelockedCallTimestamp",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimelockDurationSeconds",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "executeTimelockedCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecuteTimelockedCallTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimelockDurationSeconds",
    data: BytesLike
  ): Result;
}

export namespace CallTimelockedEvent {
  export type InputTuple = [
    encodedCall: BytesLike,
    encodedCallHash: BytesLike,
    allowedAfterTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    encodedCall: string,
    encodedCallHash: string,
    allowedAfterTimestamp: bigint
  ];
  export interface OutputObject {
    encodedCall: string;
    encodedCallHash: string;
    allowedAfterTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockDurationSetEvent {
  export type InputTuple = [timelockDurationSeconds: BigNumberish];
  export type OutputTuple = [timelockDurationSeconds: bigint];
  export interface OutputObject {
    timelockDurationSeconds: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockedCallCanceledEvent {
  export type InputTuple = [encodedCallHash: BytesLike];
  export type OutputTuple = [encodedCallHash: string];
  export interface OutputObject {
    encodedCallHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockedCallExecutedEvent {
  export type InputTuple = [encodedCallHash: BytesLike];
  export type OutputTuple = [encodedCallHash: string];
  export interface OutputObject {
    encodedCallHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ITimelockFacet extends BaseContract {
  connect(runner?: ContractRunner | null): ITimelockFacet;
  waitForDeployment(): Promise<this>;

  interface: ITimelockFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeTimelockedCall: TypedContractMethod<
    [_encodedCall: BytesLike],
    [void],
    "nonpayable"
  >;

  getExecuteTimelockedCallTimestamp: TypedContractMethod<
    [_encodedCall: BytesLike],
    [bigint],
    "view"
  >;

  getTimelockDurationSeconds: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeTimelockedCall"
  ): TypedContractMethod<[_encodedCall: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getExecuteTimelockedCallTimestamp"
  ): TypedContractMethod<[_encodedCall: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTimelockDurationSeconds"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "CallTimelocked"
  ): TypedContractEvent<
    CallTimelockedEvent.InputTuple,
    CallTimelockedEvent.OutputTuple,
    CallTimelockedEvent.OutputObject
  >;
  getEvent(
    key: "TimelockDurationSet"
  ): TypedContractEvent<
    TimelockDurationSetEvent.InputTuple,
    TimelockDurationSetEvent.OutputTuple,
    TimelockDurationSetEvent.OutputObject
  >;
  getEvent(
    key: "TimelockedCallCanceled"
  ): TypedContractEvent<
    TimelockedCallCanceledEvent.InputTuple,
    TimelockedCallCanceledEvent.OutputTuple,
    TimelockedCallCanceledEvent.OutputObject
  >;
  getEvent(
    key: "TimelockedCallExecuted"
  ): TypedContractEvent<
    TimelockedCallExecutedEvent.InputTuple,
    TimelockedCallExecutedEvent.OutputTuple,
    TimelockedCallExecutedEvent.OutputObject
  >;

  filters: {
    "CallTimelocked(bytes,bytes32,uint256)": TypedContractEvent<
      CallTimelockedEvent.InputTuple,
      CallTimelockedEvent.OutputTuple,
      CallTimelockedEvent.OutputObject
    >;
    CallTimelocked: TypedContractEvent<
      CallTimelockedEvent.InputTuple,
      CallTimelockedEvent.OutputTuple,
      CallTimelockedEvent.OutputObject
    >;

    "TimelockDurationSet(uint256)": TypedContractEvent<
      TimelockDurationSetEvent.InputTuple,
      TimelockDurationSetEvent.OutputTuple,
      TimelockDurationSetEvent.OutputObject
    >;
    TimelockDurationSet: TypedContractEvent<
      TimelockDurationSetEvent.InputTuple,
      TimelockDurationSetEvent.OutputTuple,
      TimelockDurationSetEvent.OutputObject
    >;

    "TimelockedCallCanceled(bytes32)": TypedContractEvent<
      TimelockedCallCanceledEvent.InputTuple,
      TimelockedCallCanceledEvent.OutputTuple,
      TimelockedCallCanceledEvent.OutputObject
    >;
    TimelockedCallCanceled: TypedContractEvent<
      TimelockedCallCanceledEvent.InputTuple,
      TimelockedCallCanceledEvent.OutputTuple,
      TimelockedCallCanceledEvent.OutputObject
    >;

    "TimelockedCallExecuted(bytes32)": TypedContractEvent<
      TimelockedCallExecutedEvent.InputTuple,
      TimelockedCallExecutedEvent.OutputTuple,
      TimelockedCallExecutedEvent.OutputObject
    >;
    TimelockedCallExecuted: TypedContractEvent<
      TimelockedCallExecutedEvent.InputTuple,
      TimelockedCallExecutedEvent.OutputTuple,
      TimelockedCallExecutedEvent.OutputObject
    >;
  };
}
