/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IXRPPaymentNonexistence {
  export type RequestBodyStruct = {
    minimalBlockNumber: BigNumberish;
    deadlineBlockNumber: BigNumberish;
    deadlineTimestamp: BigNumberish;
    destinationAddressHash: BytesLike;
    amount: BigNumberish;
    checkFirstMemoData: boolean;
    firstMemoDataHash: BytesLike;
    checkDestinationTag: boolean;
    destinationTag: BigNumberish;
    proofOwner: AddressLike;
  };

  export type RequestBodyStructOutput = [
    minimalBlockNumber: bigint,
    deadlineBlockNumber: bigint,
    deadlineTimestamp: bigint,
    destinationAddressHash: string,
    amount: bigint,
    checkFirstMemoData: boolean,
    firstMemoDataHash: string,
    checkDestinationTag: boolean,
    destinationTag: bigint,
    proofOwner: string
  ] & {
    minimalBlockNumber: bigint;
    deadlineBlockNumber: bigint;
    deadlineTimestamp: bigint;
    destinationAddressHash: string;
    amount: bigint;
    checkFirstMemoData: boolean;
    firstMemoDataHash: string;
    checkDestinationTag: boolean;
    destinationTag: bigint;
    proofOwner: string;
  };

  export type ResponseBodyStruct = {
    minimalBlockTimestamp: BigNumberish;
    firstOverflowBlockNumber: BigNumberish;
    firstOverflowBlockTimestamp: BigNumberish;
  };

  export type ResponseBodyStructOutput = [
    minimalBlockTimestamp: bigint,
    firstOverflowBlockNumber: bigint,
    firstOverflowBlockTimestamp: bigint
  ] & {
    minimalBlockTimestamp: bigint;
    firstOverflowBlockNumber: bigint;
    firstOverflowBlockTimestamp: bigint;
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IXRPPaymentNonexistence.RequestBodyStruct;
    responseBody: IXRPPaymentNonexistence.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IXRPPaymentNonexistence.RequestBodyStructOutput,
    responseBody: IXRPPaymentNonexistence.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IXRPPaymentNonexistence.RequestBodyStructOutput;
    responseBody: IXRPPaymentNonexistence.ResponseBodyStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    data: IXRPPaymentNonexistence.ResponseStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    data: IXRPPaymentNonexistence.ResponseStructOutput
  ] & {
    merkleProof: string[];
    data: IXRPPaymentNonexistence.ResponseStructOutput;
  };
}

export interface IXRPPaymentNonexistenceVerificationInterface
  extends Interface {
  getFunction(
    nameOrSignature: "verifyXRPPaymentNonexistence"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verifyXRPPaymentNonexistence",
    values: [IXRPPaymentNonexistence.ProofStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "verifyXRPPaymentNonexistence",
    data: BytesLike
  ): Result;
}

export interface IXRPPaymentNonexistenceVerification extends BaseContract {
  connect(runner?: ContractRunner | null): IXRPPaymentNonexistenceVerification;
  waitForDeployment(): Promise<this>;

  interface: IXRPPaymentNonexistenceVerificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  verifyXRPPaymentNonexistence: TypedContractMethod<
    [_proof: IXRPPaymentNonexistence.ProofStruct],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "verifyXRPPaymentNonexistence"
  ): TypedContractMethod<
    [_proof: IXRPPaymentNonexistence.ProofStruct],
    [boolean],
    "view"
  >;

  filters: {};
}
