/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IXrplProviderWalletsFacetInterface extends Interface {
  getFunction(nameOrSignature: "getXrplProviderWallets"): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "XrplProviderWalletAdded"
      | "XrplProviderWalletRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getXrplProviderWallets",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getXrplProviderWallets",
    data: BytesLike
  ): Result;
}

export namespace XrplProviderWalletAddedEvent {
  export type InputTuple = [xrplProviderWallet: string];
  export type OutputTuple = [xrplProviderWallet: string];
  export interface OutputObject {
    xrplProviderWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XrplProviderWalletRemovedEvent {
  export type InputTuple = [xrplProviderWallet: string];
  export type OutputTuple = [xrplProviderWallet: string];
  export interface OutputObject {
    xrplProviderWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IXrplProviderWalletsFacet extends BaseContract {
  connect(runner?: ContractRunner | null): IXrplProviderWalletsFacet;
  waitForDeployment(): Promise<this>;

  interface: IXrplProviderWalletsFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getXrplProviderWallets: TypedContractMethod<[], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getXrplProviderWallets"
  ): TypedContractMethod<[], [string[]], "view">;

  getEvent(
    key: "XrplProviderWalletAdded"
  ): TypedContractEvent<
    XrplProviderWalletAddedEvent.InputTuple,
    XrplProviderWalletAddedEvent.OutputTuple,
    XrplProviderWalletAddedEvent.OutputObject
  >;
  getEvent(
    key: "XrplProviderWalletRemoved"
  ): TypedContractEvent<
    XrplProviderWalletRemovedEvent.InputTuple,
    XrplProviderWalletRemovedEvent.OutputTuple,
    XrplProviderWalletRemovedEvent.OutputObject
  >;

  filters: {
    "XrplProviderWalletAdded(string)": TypedContractEvent<
      XrplProviderWalletAddedEvent.InputTuple,
      XrplProviderWalletAddedEvent.OutputTuple,
      XrplProviderWalletAddedEvent.OutputObject
    >;
    XrplProviderWalletAdded: TypedContractEvent<
      XrplProviderWalletAddedEvent.InputTuple,
      XrplProviderWalletAddedEvent.OutputTuple,
      XrplProviderWalletAddedEvent.OutputObject
    >;

    "XrplProviderWalletRemoved(string)": TypedContractEvent<
      XrplProviderWalletRemovedEvent.InputTuple,
      XrplProviderWalletRemovedEvent.OutputTuple,
      XrplProviderWalletRemovedEvent.OutputObject
    >;
    XrplProviderWalletRemoved: TypedContractEvent<
      XrplProviderWalletRemovedEvent.InputTuple,
      XrplProviderWalletRemovedEvent.OutputTuple,
      XrplProviderWalletRemovedEvent.OutputObject
    >;
  };
}
