/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IWeb2Json {
  export type RequestBodyStruct = {
    url: string;
    httpMethod: string;
    headers: string;
    queryParams: string;
    body: string;
    postProcessJq: string;
    abiSignature: string;
  };

  export type RequestBodyStructOutput = [
    url: string,
    httpMethod: string,
    headers: string,
    queryParams: string,
    body: string,
    postProcessJq: string,
    abiSignature: string
  ] & {
    url: string;
    httpMethod: string;
    headers: string;
    queryParams: string;
    body: string;
    postProcessJq: string;
    abiSignature: string;
  };

  export type ResponseBodyStruct = { abiEncodedData: BytesLike };

  export type ResponseBodyStructOutput = [abiEncodedData: string] & {
    abiEncodedData: string;
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IWeb2Json.RequestBodyStruct;
    responseBody: IWeb2Json.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IWeb2Json.RequestBodyStructOutput,
    responseBody: IWeb2Json.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IWeb2Json.RequestBodyStructOutput;
    responseBody: IWeb2Json.ResponseBodyStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    data: IWeb2Json.ResponseStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    data: IWeb2Json.ResponseStructOutput
  ] & { merkleProof: string[]; data: IWeb2Json.ResponseStructOutput };
}

export interface FdcWeb2JsonResolverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "configs"
      | "getOutcome"
      | "isResolved"
      | "registerMarket"
      | "resolveWithProof"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MarketRegistered" | "OutcomeResolved"
  ): EventFragment;

  encodeFunctionData(functionFragment: "configs", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getOutcome",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isResolved",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerMarket",
    values: [BytesLike, IWeb2Json.RequestBodyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveWithProof",
    values: [BytesLike, IWeb2Json.ProofStruct]
  ): string;

  decodeFunctionResult(functionFragment: "configs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOutcome", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isResolved", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveWithProof",
    data: BytesLike
  ): Result;
}

export namespace MarketRegisteredEvent {
  export type InputTuple = [
    marketId: BytesLike,
    expectedRequestHash: BytesLike
  ];
  export type OutputTuple = [marketId: string, expectedRequestHash: string];
  export interface OutputObject {
    marketId: string;
    expectedRequestHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OutcomeResolvedEvent {
  export type InputTuple = [marketId: BytesLike, outcome: BigNumberish];
  export type OutputTuple = [marketId: string, outcome: bigint];
  export interface OutputObject {
    marketId: string;
    outcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FdcWeb2JsonResolver extends BaseContract {
  connect(runner?: ContractRunner | null): FdcWeb2JsonResolver;
  waitForDeployment(): Promise<this>;

  interface: FdcWeb2JsonResolverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  configs: TypedContractMethod<
    [arg0: BytesLike],
    [[string, boolean] & { expectedRequestHash: string; registered: boolean }],
    "view"
  >;

  getOutcome: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  isResolved: TypedContractMethod<[marketId: BytesLike], [boolean], "view">;

  registerMarket: TypedContractMethod<
    [marketId: BytesLike, requestBody: IWeb2Json.RequestBodyStruct],
    [void],
    "nonpayable"
  >;

  resolveWithProof: TypedContractMethod<
    [marketId: BytesLike, proof: IWeb2Json.ProofStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "configs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[string, boolean] & { expectedRequestHash: string; registered: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOutcome"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isResolved"
  ): TypedContractMethod<[marketId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerMarket"
  ): TypedContractMethod<
    [marketId: BytesLike, requestBody: IWeb2Json.RequestBodyStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveWithProof"
  ): TypedContractMethod<
    [marketId: BytesLike, proof: IWeb2Json.ProofStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MarketRegistered"
  ): TypedContractEvent<
    MarketRegisteredEvent.InputTuple,
    MarketRegisteredEvent.OutputTuple,
    MarketRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OutcomeResolved"
  ): TypedContractEvent<
    OutcomeResolvedEvent.InputTuple,
    OutcomeResolvedEvent.OutputTuple,
    OutcomeResolvedEvent.OutputObject
  >;

  filters: {
    "MarketRegistered(bytes32,bytes32)": TypedContractEvent<
      MarketRegisteredEvent.InputTuple,
      MarketRegisteredEvent.OutputTuple,
      MarketRegisteredEvent.OutputObject
    >;
    MarketRegistered: TypedContractEvent<
      MarketRegisteredEvent.InputTuple,
      MarketRegisteredEvent.OutputTuple,
      MarketRegisteredEvent.OutputObject
    >;

    "OutcomeResolved(bytes32,uint8)": TypedContractEvent<
      OutcomeResolvedEvent.InputTuple,
      OutcomeResolvedEvent.OutputTuple,
      OutcomeResolvedEvent.OutputObject
    >;
    OutcomeResolved: TypedContractEvent<
      OutcomeResolvedEvent.InputTuple,
      OutcomeResolvedEvent.OutputTuple,
      OutcomeResolvedEvent.OutputObject
    >;
  };
}
