/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FtsoPriceResolverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "configs"
      | "getOutcome"
      | "isResolved"
      | "registerMarket"
      | "resolve"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MarketRegistered" | "OutcomeResolved"
  ): EventFragment;

  encodeFunctionData(functionFragment: "configs", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getOutcome",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isResolved",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerMarket",
    values: [
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "resolve", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "configs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOutcome", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isResolved", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolve", data: BytesLike): Result;
}

export namespace MarketRegisteredEvent {
  export type InputTuple = [
    marketId: BytesLike,
    feedId: BytesLike,
    strikeValue: BigNumberish,
    strikeDecimals: BigNumberish,
    resolveYesIfAtOrAbove: boolean,
    resolvesAfter: BigNumberish
  ];
  export type OutputTuple = [
    marketId: string,
    feedId: string,
    strikeValue: bigint,
    strikeDecimals: bigint,
    resolveYesIfAtOrAbove: boolean,
    resolvesAfter: bigint
  ];
  export interface OutputObject {
    marketId: string;
    feedId: string;
    strikeValue: bigint;
    strikeDecimals: bigint;
    resolveYesIfAtOrAbove: boolean;
    resolvesAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OutcomeResolvedEvent {
  export type InputTuple = [marketId: BytesLike, outcome: BigNumberish];
  export type OutputTuple = [marketId: string, outcome: bigint];
  export interface OutputObject {
    marketId: string;
    outcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FtsoPriceResolver extends BaseContract {
  connect(runner?: ContractRunner | null): FtsoPriceResolver;
  waitForDeployment(): Promise<this>;

  interface: FtsoPriceResolverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  configs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean, bigint, boolean] & {
        feedId: string;
        strikeValue: bigint;
        strikeDecimals: bigint;
        resolveYesIfAtOrAbove: boolean;
        resolvesAfter: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;

  getOutcome: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  isResolved: TypedContractMethod<[marketId: BytesLike], [boolean], "view">;

  registerMarket: TypedContractMethod<
    [
      marketId: BytesLike,
      feedId: BytesLike,
      strikeValue: BigNumberish,
      strikeDecimals: BigNumberish,
      resolveYesIfAtOrAbove: boolean,
      resolvesAfter: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  resolve: TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "configs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean, bigint, boolean] & {
        feedId: string;
        strikeValue: bigint;
        strikeDecimals: bigint;
        resolveYesIfAtOrAbove: boolean;
        resolvesAfter: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOutcome"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isResolved"
  ): TypedContractMethod<[marketId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerMarket"
  ): TypedContractMethod<
    [
      marketId: BytesLike,
      feedId: BytesLike,
      strikeValue: BigNumberish,
      strikeDecimals: BigNumberish,
      resolveYesIfAtOrAbove: boolean,
      resolvesAfter: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolve"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "MarketRegistered"
  ): TypedContractEvent<
    MarketRegisteredEvent.InputTuple,
    MarketRegisteredEvent.OutputTuple,
    MarketRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OutcomeResolved"
  ): TypedContractEvent<
    OutcomeResolvedEvent.InputTuple,
    OutcomeResolvedEvent.OutputTuple,
    OutcomeResolvedEvent.OutputObject
  >;

  filters: {
    "MarketRegistered(bytes32,bytes21,uint256,int8,bool,uint256)": TypedContractEvent<
      MarketRegisteredEvent.InputTuple,
      MarketRegisteredEvent.OutputTuple,
      MarketRegisteredEvent.OutputObject
    >;
    MarketRegistered: TypedContractEvent<
      MarketRegisteredEvent.InputTuple,
      MarketRegisteredEvent.OutputTuple,
      MarketRegisteredEvent.OutputObject
    >;

    "OutcomeResolved(bytes32,uint8)": TypedContractEvent<
      OutcomeResolvedEvent.InputTuple,
      OutcomeResolvedEvent.OutputTuple,
      OutcomeResolvedEvent.OutputObject
    >;
    OutcomeResolved: TypedContractEvent<
      OutcomeResolvedEvent.InputTuple,
      OutcomeResolvedEvent.OutputTuple,
      OutcomeResolvedEvent.OutputObject
    >;
  };
}
