/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FdcWeb2JsonResolver } from "./FdcWeb2JsonResolver";
export type { FtsoPriceResolver } from "./FtsoPriceResolver";
export type { ManualResolver } from "./ManualResolver";
