/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAssetManagerController,
  IAssetManagerControllerInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IAssetManagerController";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "assetManager",
        type: "address",
      },
    ],
    name: "AssetManagerAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "assetManager",
        type: "address",
      },
    ],
    name: "AssetManagerRemoved",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_assetManager",
        type: "address",
      },
    ],
    name: "assetManagerExists",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAssetManagers",
    outputs: [
      {
        internalType: "contract IAssetManager[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAssetManagerController__factory {
  static readonly abi = _abi;
  static createInterface(): IAssetManagerControllerInterface {
    return new Interface(_abi) as IAssetManagerControllerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAssetManagerController {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAssetManagerController;
  }
}
