/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IExecutorsFacet,
  IExecutorsFacetInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IExecutorsFacet";

const _abi = [
  {
    inputs: [],
    name: "InvalidExecutor",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidExecutorFee",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "executorFee",
        type: "uint256",
      },
    ],
    name: "ExecutorFeeSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "executor",
        type: "address",
      },
    ],
    name: "ExecutorSet",
    type: "event",
  },
  {
    inputs: [],
    name: "getExecutorInfo",
    outputs: [
      {
        internalType: "address payable",
        name: "_executor",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_executorFee",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IExecutorsFacet__factory {
  static readonly abi = _abi;
  static createInterface(): IExecutorsFacetInterface {
    return new Interface(_abi) as IExecutorsFacetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IExecutorsFacet {
    return new Contract(address, _abi, runner) as unknown as IExecutorsFacet;
  }
}
