/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPaymentProofsFacet,
  IPaymentProofsFacetInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IPaymentProofsFacet";

const _abi = [
  {
    inputs: [],
    name: "InvalidPaymentProofValidityDuration",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidReceivingAddressHash",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidSourceId",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidTransactionProof",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidTransactionStatus",
    type: "error",
  },
  {
    inputs: [],
    name: "MismatchingSourceAndXrplAddr",
    type: "error",
  },
  {
    inputs: [],
    name: "PaymentProofExpired",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "paymentProofValidityDurationSeconds",
        type: "uint256",
      },
    ],
    name: "PaymentProofValidityDurationSecondsSet",
    type: "event",
  },
  {
    inputs: [],
    name: "getPaymentProofValidityDurationSeconds",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSourceId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPaymentProofsFacet__factory {
  static readonly abi = _abi;
  static createInterface(): IPaymentProofsFacetInterface {
    return new Interface(_abi) as IPaymentProofsFacetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPaymentProofsFacet {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPaymentProofsFacet;
  }
}
