/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPersonalAccountsFacet,
  IPersonalAccountsFacetInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IPersonalAccountsFacet";

const _abi = [
  {
    inputs: [],
    name: "InvalidPersonalAccountImplementation",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "personalAccountAddress",
        type: "address",
      },
    ],
    name: "PersonalAccountNotSuccessfullyDeployed",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "personalAccount",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "xrplOwner",
        type: "string",
      },
    ],
    name: "PersonalAccountCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "newImplementation",
        type: "address",
      },
    ],
    name: "PersonalAccountImplementationSet",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_xrplOwner",
        type: "string",
      },
    ],
    name: "getPersonalAccount",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPersonalAccountsFacet__factory {
  static readonly abi = _abi;
  static createInterface(): IPersonalAccountsFacetInterface {
    return new Interface(_abi) as IPersonalAccountsFacetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPersonalAccountsFacet {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPersonalAccountsFacet;
  }
}
