/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRedemptionTimeExtension,
  IRedemptionTimeExtensionInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IRedemptionTimeExtension";

const _abi = [
  {
    inputs: [],
    name: "redemptionPaymentExtensionSeconds",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
    ],
    name: "setRedemptionPaymentExtensionSeconds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRedemptionTimeExtension__factory {
  static readonly abi = _abi;
  static createInterface(): IRedemptionTimeExtensionInterface {
    return new Interface(_abi) as IRedemptionTimeExtensionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRedemptionTimeExtension {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IRedemptionTimeExtension;
  }
}
