/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRedeemExtendedSettings,
  IRedeemExtendedSettingsInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IRedeemExtendedSettings";

const _abi = [
  {
    inputs: [],
    name: "minimumRedeemAmountUBA",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_valueUBA",
        type: "uint256",
      },
    ],
    name: "setMinimumRedeemAmountUBA",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_feeBIPS",
        type: "uint256",
      },
    ],
    name: "setSystemRedemptionFeeBIPS",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_receiver",
        type: "address",
      },
    ],
    name: "setSystemRedemptionFeeReceiver",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "systemRedemptionFeeBIPS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "systemRedemptionFeeReceiver",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRedeemExtendedSettings__factory {
  static readonly abi = _abi;
  static createInterface(): IRedeemExtendedSettingsInterface {
    return new Interface(_abi) as IRedeemExtendedSettingsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRedeemExtendedSettings {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IRedeemExtendedSettings;
  }
}
