/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVaultsFacet,
  IVaultsFacetInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IVaultsFacet";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
    ],
    name: "InvalidVaultId",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "enum IVaultsFacet.VaultType",
        name: "vaultType",
        type: "uint8",
      },
    ],
    name: "InvalidVaultType",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "vaultAddress",
        type: "address",
      },
    ],
    name: "VaultAddressAlreadyAdded",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "VaultAddressZero",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
    ],
    name: "VaultIdAlreadyAdded",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "VaultIdZero",
    type: "error",
  },
  {
    inputs: [],
    name: "VaultsLengthsMismatch",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "vaultAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "enum IVaultsFacet.VaultType",
        name: "vaultType",
        type: "uint8",
      },
    ],
    name: "VaultAdded",
    type: "event",
  },
  {
    inputs: [],
    name: "getVaults",
    outputs: [
      {
        internalType: "uint256[]",
        name: "_vaultIds",
        type: "uint256[]",
      },
      {
        internalType: "address[]",
        name: "_vaultAddresses",
        type: "address[]",
      },
      {
        internalType: "enum IVaultsFacet.VaultType[]",
        name: "_vaultTypes",
        type: "uint8[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IVaultsFacet__factory {
  static readonly abi = _abi;
  static createInterface(): IVaultsFacetInterface {
    return new Interface(_abi) as IVaultsFacetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVaultsFacet {
    return new Contract(address, _abi, runner) as unknown as IVaultsFacet;
  }
}
