/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IXrplProviderWalletsFacet,
  IXrplProviderWalletsFacetInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IXrplProviderWalletsFacet";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "xrplProviderWallet",
        type: "string",
      },
    ],
    name: "InvalidXrplProviderWallet",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "xrplProviderWallet",
        type: "string",
      },
    ],
    name: "XrplProviderWalletAlreadyExists",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "xrplProviderWallet",
        type: "string",
      },
    ],
    name: "XrplProviderWalletAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "xrplProviderWallet",
        type: "string",
      },
    ],
    name: "XrplProviderWalletRemoved",
    type: "event",
  },
  {
    inputs: [],
    name: "getXrplProviderWallets",
    outputs: [
      {
        internalType: "string[]",
        name: "",
        type: "string[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IXrplProviderWalletsFacet__factory {
  static readonly abi = _abi;
  static createInterface(): IXrplProviderWalletsFacetInterface {
    return new Interface(_abi) as IXrplProviderWalletsFacetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IXrplProviderWalletsFacet {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IXrplProviderWalletsFacet;
  }
}
