/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IXRPPaymentVerification,
  IXRPPaymentVerificationInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IXRPPaymentVerification";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32[]",
            name: "merkleProof",
            type: "bytes32[]",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "attestationType",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "sourceId",
                type: "bytes32",
              },
              {
                internalType: "uint64",
                name: "votingRound",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "lowestUsedTimestamp",
                type: "uint64",
              },
              {
                components: [
                  {
                    internalType: "bytes32",
                    name: "transactionId",
                    type: "bytes32",
                  },
                  {
                    internalType: "address",
                    name: "proofOwner",
                    type: "address",
                  },
                ],
                internalType: "struct IXRPPayment.RequestBody",
                name: "requestBody",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint64",
                    name: "blockNumber",
                    type: "uint64",
                  },
                  {
                    internalType: "uint64",
                    name: "blockTimestamp",
                    type: "uint64",
                  },
                  {
                    internalType: "string",
                    name: "sourceAddress",
                    type: "string",
                  },
                  {
                    internalType: "bytes32",
                    name: "sourceAddressHash",
                    type: "bytes32",
                  },
                  {
                    internalType: "bytes32",
                    name: "receivingAddressHash",
                    type: "bytes32",
                  },
                  {
                    internalType: "bytes32",
                    name: "intendedReceivingAddressHash",
                    type: "bytes32",
                  },
                  {
                    internalType: "int256",
                    name: "spentAmount",
                    type: "int256",
                  },
                  {
                    internalType: "int256",
                    name: "intendedSpentAmount",
                    type: "int256",
                  },
                  {
                    internalType: "int256",
                    name: "receivedAmount",
                    type: "int256",
                  },
                  {
                    internalType: "int256",
                    name: "intendedReceivedAmount",
                    type: "int256",
                  },
                  {
                    internalType: "bool",
                    name: "hasMemoData",
                    type: "bool",
                  },
                  {
                    internalType: "bytes",
                    name: "firstMemoData",
                    type: "bytes",
                  },
                  {
                    internalType: "bool",
                    name: "hasDestinationTag",
                    type: "bool",
                  },
                  {
                    internalType: "uint256",
                    name: "destinationTag",
                    type: "uint256",
                  },
                  {
                    internalType: "uint8",
                    name: "status",
                    type: "uint8",
                  },
                ],
                internalType: "struct IXRPPayment.ResponseBody",
                name: "responseBody",
                type: "tuple",
              },
            ],
            internalType: "struct IXRPPayment.Response",
            name: "data",
            type: "tuple",
          },
        ],
        internalType: "struct IXRPPayment.Proof",
        name: "_proof",
        type: "tuple",
      },
    ],
    name: "verifyXRPPayment",
    outputs: [
      {
        internalType: "bool",
        name: "_proved",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IXRPPaymentVerification__factory {
  static readonly abi = _abi;
  static createInterface(): IXRPPaymentVerificationInterface {
    return new Interface(_abi) as IXRPPaymentVerificationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IXRPPaymentVerification {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IXRPPaymentVerification;
  }
}
