/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IXRPPaymentNonexistenceVerification,
  IXRPPaymentNonexistenceVerificationInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IXRPPaymentNonexistenceVerification";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32[]",
            name: "merkleProof",
            type: "bytes32[]",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "attestationType",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "sourceId",
                type: "bytes32",
              },
              {
                internalType: "uint64",
                name: "votingRound",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "lowestUsedTimestamp",
                type: "uint64",
              },
              {
                components: [
                  {
                    internalType: "uint64",
                    name: "minimalBlockNumber",
                    type: "uint64",
                  },
                  {
                    internalType: "uint64",
                    name: "deadlineBlockNumber",
                    type: "uint64",
                  },
                  {
                    internalType: "uint64",
                    name: "deadlineTimestamp",
                    type: "uint64",
                  },
                  {
                    internalType: "bytes32",
                    name: "destinationAddressHash",
                    type: "bytes32",
                  },
                  {
                    internalType: "uint256",
                    name: "amount",
                    type: "uint256",
                  },
                  {
                    internalType: "bool",
                    name: "checkFirstMemoData",
                    type: "bool",
                  },
                  {
                    internalType: "bytes32",
                    name: "firstMemoDataHash",
                    type: "bytes32",
                  },
                  {
                    internalType: "bool",
                    name: "checkDestinationTag",
                    type: "bool",
                  },
                  {
                    internalType: "uint256",
                    name: "destinationTag",
                    type: "uint256",
                  },
                  {
                    internalType: "address",
                    name: "proofOwner",
                    type: "address",
                  },
                ],
                internalType: "struct IXRPPaymentNonexistence.RequestBody",
                name: "requestBody",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint64",
                    name: "minimalBlockTimestamp",
                    type: "uint64",
                  },
                  {
                    internalType: "uint64",
                    name: "firstOverflowBlockNumber",
                    type: "uint64",
                  },
                  {
                    internalType: "uint64",
                    name: "firstOverflowBlockTimestamp",
                    type: "uint64",
                  },
                ],
                internalType: "struct IXRPPaymentNonexistence.ResponseBody",
                name: "responseBody",
                type: "tuple",
              },
            ],
            internalType: "struct IXRPPaymentNonexistence.Response",
            name: "data",
            type: "tuple",
          },
        ],
        internalType: "struct IXRPPaymentNonexistence.Proof",
        name: "_proof",
        type: "tuple",
      },
    ],
    name: "verifyXRPPaymentNonexistence",
    outputs: [
      {
        internalType: "bool",
        name: "_proved",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IXRPPaymentNonexistenceVerification__factory {
  static readonly abi = _abi;
  static createInterface(): IXRPPaymentNonexistenceVerificationInterface {
    return new Interface(_abi) as IXRPPaymentNonexistenceVerificationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IXRPPaymentNonexistenceVerification {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IXRPPaymentNonexistenceVerification;
  }
}
