const solc = require("solc");
const fs = require("fs");
const path = require("path");

function findImports(importPath) {
  const candidates = [
    path.resolve(__dirname, importPath),
    path.resolve(__dirname, "node_modules", importPath),
    path.resolve(__dirname, "../../node_modules", importPath),
  ];
  for (const c of candidates) {
    if (fs.existsSync(c)) {
      return { contents: fs.readFileSync(c, "utf8") };
    }
  }
  return { error: "File not found: " + importPath };
}

const contractsDir = path.resolve(__dirname, "contracts");

function listSolFiles(dir) {
  let results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results = results.concat(listSolFiles(full));
    else if (entry.name.endsWith(".sol")) results.push(full);
  }
  return results;
}

const sources = {};
for (const file of listSolFiles(contractsDir)) {
  const rel = "contracts/" + path.relative(contractsDir, file);
  sources[rel] = { content: fs.readFileSync(file, "utf8") };
}

const input = {
  language: "Solidity",
  sources,
  settings: {
    outputSelection: { "*": { "*": ["abi"] } },
    optimizer: { enabled: true, runs: 200 },
    evmVersion: "cancun",
  },
};

const output = JSON.parse(
  solc.compile(JSON.stringify(input), { import: findImports }),
);

let hasError = false;
if (output.errors) {
  for (const err of output.errors) {
    if (err.severity === "error") {
      hasError = true;
      console.error("\n" + err.formattedMessage);
    }
  }
}
if (hasError) process.exit(1);

// Contracts the frontend/backend actually need ABIs for.
const TARGETS = {
  "contracts/PolycastMarket.sol": "PolycastMarket",
  "contracts/PolycastMarketFactory.sol": "PolycastMarketFactory",
  "contracts/PolycastAMM.sol": "PolycastAMM",
  "contracts/PolycastAMMFactory.sol": "PolycastAMMFactory",
  "contracts/oracles/PolymarketPriceOracle.sol": "PolymarketPriceOracle",
  "contracts/oracles/PolycastOracleMinter.sol": "PolycastOracleMinter",
  "contracts/oracles/PolycastOracleMinterFactory.sol": "PolycastOracleMinterFactory",
  "contracts/resolvers/ManualResolver.sol": "ManualResolver",
};

const outDir = path.resolve(__dirname, "../abi/generated");
fs.mkdirSync(outDir, { recursive: true });

for (const [file, name] of Object.entries(TARGETS)) {
  const abi = output.contracts[file]?.[name]?.abi;
  if (!abi) {
    console.error("Missing ABI for", name, "in", file);
    process.exit(1);
  }
  const varName = name.charAt(0).toLowerCase() + name.slice(1) + "Abi";
  const content = `// AUTO-GENERATED by packages/contracts/export-abi.js — do not edit by hand.
// Regenerate with: node export-abi.js (from packages/contracts)

export const ${varName} = ${JSON.stringify(abi, null, 2)} as const;
`;
  fs.writeFileSync(path.join(outDir, `${name}.ts`), content);
  console.log("Wrote", `packages/abi/generated/${name}.ts`);
}
